"use strict";
/* Vet Clinical Toolbox 5.0-r08 · Clinical OS 3.1 upgrade layer
 * Adds bedside rounds, I/O balance, antimicrobial timeout, lab snapshots,
 * discharge readiness and AI re-evaluation without changing product version.
 */
(function(){
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), now=()=>new Date().toISOString();
  const patient=()=>window.VCT50_PATIENT_STATE||{};
  const os=()=>window.VCT50_CLINICAL_OS_STATE||{problemList:[],tasks:[],timeline:[],labs:[],audit:[]};
  function save(){const s=os();s.version='5.0-r08';localStorage.setItem('vct50_clinical_os_state_v2',JSON.stringify(s));window.VCT50_CLINICAL_OS_STATE=s;window.VCT50_CLINICAL_OS?.renderAll?.()}
  function addEvent(text,type='Clinical OS'){const s=os();s.timeline=Array.isArray(s.timeline)?s.timeline:[];s.timeline.push({time:now(),type,text,patientId:patient().patientId||''});s.timeline=s.timeline.slice(-300);save()}
  function inject(){
    const root=$('clinicalOS'); if(!root||$('vctClinicalOSUpgrade'))return;
    const card=document.createElement('div');card.id='vctClinicalOSUpgrade';card.className='card';
    card.innerHTML=`<div class="vct3-head"><div><div class="eyebrow">BEDSIDE WORKFLOW · CLINICAL OS 3.1</div><h3>一线临床工作台 · Bedside Rounds（查房）</h3><p class="os-muted">把“检查—治疗—监测—复评”变成可执行任务，而不是只停留在建议层面。</p></div><span id="vctRoundStatus" class="os-chip os-blue">Ready（待查房）</span></div>
      <div class="vct3-grid">
        <section class="vct3-panel"><h4>① Rounds Checklist（查房核查）</h4><div id="vctRoundsList" class="vct3-list"></div><button class="primary" id="vctRoundsSave">完成本次查房记录</button></section>
        <section class="vct3-panel"><h4>② Fluid / I&O（液体与出入量）</h4><div class="vct3-form"><label>输入量 mL<input id="vctIn" type="number" step="0.1"></label><label>尿量 mL<input id="vctUop" type="number" step="0.1"></label><label>呕吐/腹泻 mL<input id="vctLossGI" type="number" step="0.1"></label><label>引流/其他 mL<input id="vctLossOther" type="number" step="0.1"></label><label>当前体重 kg<input id="vctWeight" type="number" step="0.01"></label></div><button class="primary" id="vctBalanceCalc">计算本时段净平衡</button><div id="vctBalanceOut"></div></section>
        <section class="vct3-panel"><h4>③ Antimicrobial Timeout（抗菌药复盘）</h4><label>当前抗菌药<textarea id="vctAbx" placeholder="药名/方案；可多项"></textarea></label><div class="vct3-form"><label>感染依据<select id="vctAbxEvidence"><option>明确感染/培养支持</option><option>高度疑似</option><option>证据不足</option><option>预防性使用</option></select></label><label>治疗日<input id="vctAbxDay" type="number" min="1"></label></div><label><input type="checkbox" id="vctCulture"> 已获取/计划获取培养与药敏（适用时）</label><label><input type="checkbox" id="vctDeescalate"> 已考虑停药/降阶/窄谱化</label><button class="primary" id="vctAbxSave">记录抗菌药复盘</button><div id="vctAbxOut"></div></section>
        <section class="vct3-panel"><h4>④ Lab Snapshot（检验快照）</h4><div class="vct3-form"><label>指标<select id="vctLabName"><option>Creatinine</option><option>Urea/BUN</option><option>Potassium</option><option>Sodium</option><option>Glucose</option><option>Albumin</option><option>Lactate</option><option>PCV/HCT</option><option>Total Protein</option><option>ALT</option><option>AST</option></select></label><label>数值<input id="vctLabValue" type="number" step="0.01"></label><label>单位<input id="vctLabUnit" placeholder="mmol/L, mg/dL, g/L..."></label></div><button class="primary" id="vctLabSave">记录检验结果</button><div id="vctLabOut"></div></section>
        <section class="vct3-panel"><h4>⑤ Discharge Readiness（出院准备）</h4><div id="vctDischargeList" class="vct3-list"></div><button class="primary" id="vctDischargeSave">生成出院记录任务</button><div id="vctDischargeOut"></div></section>
        <section class="vct3-panel"><h4>⑥ AI Re-evaluation（二次临床推理）</h4><p class="os-muted">治疗或新检查结果出现后，不要重复问“现在怎么办”，而要让AI比较<strong>前后状态变化</strong>。</p><button class="primary" id="vctAiReeval">带最新患者状态重新分析</button><div id="vctAiReevalOut"></div></section>
      </div>`;
    const anchor=[...root.querySelectorAll('.card')].pop(); root.insertBefore(card,anchor||null);
    style(); renderRounds(); renderDischarge();
    $('vctRoundsSave').onclick=()=>{const checked=[...document.querySelectorAll('#vctRoundsList input:checked')].map(x=>x.value);addEvent('查房完成：'+checked.join('、'),'查房');$('vctRoundStatus').textContent='Recorded（已记录）'};
    $('vctBalanceCalc').onclick=balance;
    $('vctAbxSave').onclick=abx;
    $('vctLabSave').onclick=lab;
    $('vctDischargeSave').onclick=discharge;
    $('vctAiReeval').onclick=reeval;
    window.addEventListener('vct50:patient-change',()=>{renderRounds();renderDischarge()});
  }
  function renderRounds(){const p=patient(),s=os();const risks=window.VCT50_CLINICAL_OS?.risks?.()||[];const meds=p.currentMeds||'';const items=[
    ['identity','Patient identity / species / weight confirmed（患者身份/物种/体重）'],['vitals','Current vitals reviewed（当前生命体征）'],['perfusion','Perfusion / BP / mentation reviewed（灌注/血压/意识）'],['resp','Respiratory status reviewed（呼吸状态）'],['pain','Pain score / comfort reviewed（疼痛/舒适度）'],['intake','Nutrition + GI intake/output reviewed（营养及胃肠摄入/排出）'],['urine','Urine output reviewed（尿量）'],['labs','New laboratory results reviewed（新检验结果）'],['meds','Medication list + adverse effects reviewed（用药及不良反应）'],['goals','Treatment goals and reassessment time documented（治疗目标及复评时间）']];
    if(/抗菌|阿莫西林|头孢|氨基糖苷|氟喹诺酮|甲硝唑|多西环素|恩诺沙星|marbofloxacin/i.test(meds))items.splice(8,0,['abx','Antimicrobial timeout considered（抗菌药复盘）']);
    $('vctRoundsList').innerHTML=items.map(x=>`<label class="vct3-check"><input type="checkbox" value="${esc(x[0])}"> ${esc(x[1])}</label>`).join('')+(risks.length?`<div class="os-warning">当前内置红旗：${esc(risks.slice(0,3).map(x=>x[1]).join('；'))}</div>`:'');
  }
  function balance(){const n=id=>Number($(id).value)||0;const input=n('vctIn'),out=n('vctUop')+n('vctLossGI')+n('vctLossOther'),net=input-out,w=Number($('vctWeight').value)||Number(patient().weight)||0;const perKg=w?net/w:null;$('vctBalanceOut').innerHTML=`<div class="os-note"><b>净液体平衡：</b>${net.toFixed(1)} mL${perKg!=null?` · ${perKg.toFixed(2)} mL/kg`:''}</div><div class="os-warning">液体平衡必须结合灌注、呼吸状态、体重趋势、尿量和疾病背景动态解释；不能仅依据单次净平衡决定继续或停止输液。</div>`;addEvent(`I/O记录：输入 ${input} mL；输出 ${out} mL；净 ${net.toFixed(1)} mL`,'液体监测')}
  function abx(){const drug=$('vctAbx').value.trim();if(!drug){$('vctAbxOut').innerHTML='<div class="os-warning">请先记录当前抗菌药。</div>';return}const evidence=$('vctAbxEvidence').value,day=$('vctAbxDay').value||'未记录',culture=$('vctCulture').checked,de=$('vctDeescalate').checked;const msg=`抗菌药：${drug}；依据：${evidence}；治疗日：${day}；培养/药敏：${culture?'已考虑':'未记录'}；停药/降阶复盘：${de?'已考虑':'未完成'}`;$('vctAbxOut').innerHTML=`<div class="${evidence==='证据不足'?'os-critical':'os-note'}">${esc(msg)}</div><div class="os-muted">抗菌药应持续复核适应证、培养/药敏可行性、疗效、不良反应及是否需要窄谱化/停药。不得把“发热”本身当作细菌感染证据。</div>`;addEvent(msg,'抗菌药复盘')}
  function lab(){const name=$('vctLabName').value,val=Number($('vctLabValue').value),unit=$('vctLabUnit').value.trim();if(!Number.isFinite(val)){ $('vctLabOut').innerHTML='<div class="os-warning">请输入有效数值。</div>';return}const s=os();s.labs=Array.isArray(s.labs)?s.labs:[];s.labs.push({time:now(),name,value:val,unit,patientId:patient().patientId||'',source:'manual'});s.labs=s.labs.slice(-300);localStorage.setItem('vct50_clinical_os_state_v2',JSON.stringify(s));window.VCT50_CLINICAL_OS_STATE=s;$('vctLabOut').innerHTML=`<div class="os-note">✓ 已记录 ${esc(name)} = ${esc(val)} ${esc(unit)}</div>`;addEvent(`检验记录：${name} ${val} ${unit}`,'检查')}
  function renderDischarge(){const p=patient();const items=[['stable','生命体征/灌注达到计划的稳定标准'],['oral','能够按计划摄入水分/营养或已有明确支持方案'],['pain','疼痛控制方案与复评标准明确'],['meds','出院用药已核对物种、体重、禁忌及给药方法'],['warning','主人已知晓红旗症状与返院条件'],['follow','复诊/复查时间和检查项目已确定'],['record','病历、检验结果和治疗时间轴已完整']];$('vctDischargeList').innerHTML=items.map(x=>`<label class="vct3-check"><input type="checkbox" value="${esc(x[0])}"> ${esc(x[1])}</label>`).join('')+(p.patientId?`<div class="os-muted">当前患者：${esc(p.patientId)}</div>`:'<div class="os-warning">尚未建立患者。</div>')}
  function discharge(){const checked=[...document.querySelectorAll('#vctDischargeList input:checked')].map(x=>x.value);const total=document.querySelectorAll('#vctDischargeList input').length;const complete=checked.length===total;$('vctDischargeOut').innerHTML=`<div class="${complete?'os-note':'os-warning'}">出院准备完成度：${checked.length}/${total}${complete?' · 可进入最终医生核对。':' · 尚有项目未完成。'}</div>`;addEvent(`出院准备检查：${checked.length}/${total}`,'出院准备');}
  function reeval(){const bridge=window.VCT50_AI_BRIDGE;if(!bridge){$('vctAiReevalOut').innerHTML='<div class="os-warning">AI Bridge 尚未加载。</div>';return}const q='请基于当前患者最新状态、Problem List、最新检验/监测变化和已执行/未执行任务，对上一轮临床计划进行二次推理。请明确：哪些判断仍成立、哪些鉴别诊断排序发生变化、哪些检查现在最有价值、治疗是否需要调整、哪些风险需要升级，以及下一次复评应观察什么。不要把既往AI建议视为事实。';$('aiQuestion').value=q;window.show?.('ai');setTimeout(()=>$('aiRun')?.click(),50);$('vctAiReevalOut').innerHTML='<div class="os-note">已带入最新 Clinical OS 上下文，正在进入 AI 二次推理。</div>';addEvent('启动AI二次临床推理','AI')}
  function style(){if($('vct3-style'))return;const s=document.createElement('style');s.id='vct3-style';s.textContent=`.vct3-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.vct3-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:12px}.vct3-panel{border:1px solid var(--line);border-radius:12px;padding:12px;background:#fbfdfd}.vct3-panel h4{margin-top:0}.vct3-list{display:grid;gap:7px;margin-bottom:9px}.vct3-check{display:block;padding:8px;border:1px solid var(--line);border-radius:9px;background:#fff}.vct3-check input{margin-right:6px}.vct3-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.vct3-panel textarea{min-height:70px}.vct3-panel button{margin-top:8px;min-height:40px}@media(max-width:800px){.vct3-grid{grid-template-columns:1fr}.vct3-head{flex-direction:column}.vct3-form{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function boot(){setTimeout(inject,0)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  window.VCT50_CLINICAL_OS_UPGRADE={version:'5.0-r08-3.1'};
})();
