"use strict";
/* Vet Clinical Toolbox 5.0-r08 · Clinical OS 2.0
 * Patient-centered clinical workflow, timeline, POMR, safety, monitoring and emergency cockpit.
 * Local-first. Decision-support only; verify current labels/guidelines and real-time patient status.
 */
(function(){
  const KEY='vct50_clinical_os_state_v2';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const now=()=>new Date().toISOString();
  const patient=()=>window.VCT50_PATIENT_STATE||{};
  const safeParse=(s,d)=>{try{return JSON.parse(s)||d}catch{return d}};
  const state={version:'5.0-r08',problemList:[],vitals:[],labs:[],timeline:[],tasks:[],goals:[],allergies:[],audit:[],differentials:[]};
  function load(){const x=safeParse(localStorage.getItem(KEY),null);if(x&&typeof x==='object')Object.assign(state,x);['problemList','vitals','labs','timeline','tasks','goals','allergies','audit','differentials'].forEach(k=>{if(!Array.isArray(state[k]))state[k]=[]});}
  function save(){state.version='5.0-r08';localStorage.setItem(KEY,JSON.stringify(state));window.VCT50_CLINICAL_OS_STATE=state;}
  function audit(action,detail){state.audit.push({time:now(),action,detail:detail||'',patientId:patient().patientId||''});state.audit=state.audit.slice(-300);save();}
  function ptxt(){const p=patient();return `${p.patientId||'未建档'} · ${p.species||'犬'} · ${p.weight?`${p.weight} kg`:'体重未录入'}`;}
  function go(id){const b=document.querySelector(`nav button[data-v="${id}"]`);if(b)b.click();else if(window.show)window.show(id);window.scrollTo({top:0,behavior:'smooth'});}
  function severityClass(s){return s==='P0'?'p0':s==='P1'?'p1':s==='P2'?'p2':'p3'}
  function addStyle(){if($('vct-os-style'))return;const s=document.createElement('style');s.id='vct-os-style';s.textContent=`
  .os-hero{display:grid;grid-template-columns:1.5fr .8fr;gap:12px}.os-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px}.os-kpi{padding:10px;border:1px solid var(--line);border-radius:12px;background:#fff}.os-kpi b{font-size:21px}.os-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.os-grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.os-list{display:grid;gap:7px}.os-row{border:1px solid var(--line);border-radius:10px;padding:9px;background:#fff}.os-row small{color:#64748b}.os-chip{display:inline-block;border-radius:999px;padding:3px 8px;font-size:11px;font-weight:800;margin-right:5px}.os-red{background:#fee2e2;color:#991b1b}.os-amber{background:#ffedd5;color:#9a3412}.os-yellow{background:#fef3c7;color:#92400e}.os-green{background:#dcfce7;color:#166534}.os-blue{background:#dbeafe;color:#1e40af}.os-timeline{border-left:3px solid #cbd5e1;padding-left:14px}.os-event{position:relative;margin:0 0 10px}.os-event:before{content:'';position:absolute;left:-21px;top:5px;width:9px;height:9px;border-radius:50%;background:currentColor}.os-actions{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:8px}.os-actions button{min-height:50px}.os-emergency{background:#fff7f7;border:2px solid #fecaca}.os-timer{font-size:34px;font-weight:900;letter-spacing:1px}.os-progress{height:8px;background:#e5e7eb;border-radius:99px;overflow:hidden}.os-progress i{display:block;height:100%;background:var(--p);width:0}.os-table{width:100%;border-collapse:collapse}.os-table th,.os-table td{border-bottom:1px solid var(--line);padding:7px;text-align:left;font-size:13px}.os-muted{color:#64748b}.os-note{background:#f8fafc;border-radius:10px;padding:9px}.os-warning{padding:9px;border-left:4px solid #f59e0b;background:#fffbeb}.os-critical{padding:10px;border:2px solid #ef4444;background:#fef2f2;border-radius:10px;color:#991b1b;font-weight:700}
  @media(max-width:800px){.os-hero,.os-grid,.os-grid3{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  function inject(){
    addStyle(); if($('clinicalOS'))return;
    const nav=$('nav'); if(nav){const b=document.createElement('button');b.dataset.v='clinicalOS';b.textContent='🧠 Clinical OS（临床中枢）';b.onclick=()=>window.show?.('clinicalOS');nav.insertBefore(b,nav.firstChild);const e=document.createElement('button');e.dataset.v='osEmergency';e.textContent='🚨 Emergency（急诊）';e.onclick=()=>window.show?.('osEmergency');nav.insertBefore(e,nav.children[1]||null);}
    const main=document.querySelector('main');
    const s=document.createElement('section');s.id='clinicalOS';s.className='view';s.innerHTML=`
      <div class="card"><h2>🧠 Clinical OS 2.0（兽医临床中枢）</h2><p class="muted">Patient-centered workflow（患者中心工作流）：患者 → 风险 → 问题 → 检查 → 治疗 → 监测 → 复评。英文术语旁附中文解释，适合新手兽医快速理解。</p><div id="osCritical"></div></div>
      <div class="os-hero"><div class="card"><h3>当前患者 · Current Patient（当前患者）</h3><div id="osPatient"></div><div class="os-kpis" id="osKpis"></div></div><div class="card"><h3>快速操作 · Quick Actions（快速入口）</h3><div class="os-actions"><button class="primary" data-os-go="osEmergency">🚨 Emergency（急诊）</button><button data-os-go="clinical">🔎 Differential（鉴别）</button><button data-os-go="fluid">💧 Fluid（液体）</button><button data-os-go="dose">💊 Dose（剂量）</button><button data-os-go="anesthesia">😴 Anesthesia（麻醉）</button><button data-os-go="emergency">❤️ CPR（心肺复苏）</button><button data-os-go="ai">🤖 AI Copilot（AI助手）</button></div></div></div>
      <div class="card"><h3>Differential Diagnosis（AI鉴别诊断）</h3><div id="osAIDifferentials"></div></div>
      <div class="os-grid"><div class="card"><h3>Problem List（临床问题列表）</h3><div id="osProblems"></div><div class="toolbar"><input id="osProblemText" placeholder="例如：AKI / Hyperkalemia（高钾） / Vomiting（呕吐）"><select id="osProblemPri"><option>P0</option><option>P1</option><option selected>P2</option><option>P3</option></select><button class="primary" id="osAddProblem">添加问题</button></div></div>
      <div class="card"><h3>Next Best Test（下一项最有价值检查）</h3><div id="osNBT"></div></div></div>
      <div class="os-grid"><div class="card"><h3>Reassessment（治疗后复评）</h3><div class="toolbar"><select id="osReassessType"><option>Shock / Perfusion（休克/灌注）</option><option>Respiratory（呼吸）</option><option>AKI / Fluid（肾损伤/液体）</option><option>Pain（疼痛）</option><option>General（综合）</option></select><button class="primary" id="osReassess">生成复评清单</button></div><div id="osReassessOut"></div></div>
      <div class="card"><h3>Drug Safety（患者化用药安全）</h3><div id="osDrugSafety"></div></div></div>
      <div class="card"><h3>Timeline（病例时间轴）</h3><div class="toolbar"><input id="osEventText" placeholder="例如：09:20 lactate 5.2；完成导尿"><select id="osEventType"><option>检查</option><option>用药</option><option>输液</option><option>生命体征</option><option>手术/麻醉</option><option>输血</option><option>复评</option><option>其他</option></select><button class="primary" id="osAddEvent">记录事件</button></div><div id="osTimeline" class="os-timeline"></div></div>
      <div class="os-grid"><div class="card"><h3>Monitoring（住院监测）</h3><div class="toolbar"><button class="primary" id="osSnapshot">记录当前状态</button><button id="osClearSnapshots">清除患者快照</button></div><div id="osTrend"></div></div><div class="card"><h3>Goals & Tasks（治疗目标与任务）</h3><div class="toolbar"><input id="osTaskText" placeholder="例如：2h复查乳酸 / q4h BP"><button class="primary" id="osAddTask">添加任务</button></div><div id="osTasks"></div></div></div>
      <div class="card"><h3>POMR（问题导向病历）</h3><div id="osPOMR"></div><div class="toolbar"><button class="primary" id="osCopyContext">复制 AI 临床上下文</button><button id="osExport">导出 Clinical OS 状态</button></div></div>`;
    main.insertBefore(s,main.firstChild);
    const er=document.createElement('section');er.id='osEmergency';er.className='view';er.innerHTML=`
      <div class="card os-emergency"><h2>🚨 Emergency Cockpit（急诊驾驶舱）</h2><p class="muted">5-minute mode（5分钟模式）：先处理立即危及生命的问题，同时并行寻找病因。</p><div id="osErCritical"></div><div class="os-actions"><button class="primary" id="osErStart">▶ Start Timer（启动计时）</button><button id="osErStop">⏸ Stop（暂停）</button><button id="osErReset">↺ Reset（重置）</button></div><div class="os-timer" id="osErTimer">00:00</div></div>
      <div class="card"><h3>ABCDE（气道/呼吸/循环/神经/全身检查）</h3><div class="os-grid3"><div class="os-row"><b>A · Airway（气道）</b><select id="osA"><option>通畅</option><option>可疑</option><option>阻塞/无法维持</option></select></div><div class="os-row"><b>B · Breathing（呼吸）</b><select id="osB"><option>稳定</option><option>呼吸功增加</option><option>严重呼吸窘迫/紫绀</option></select><label>SpO₂ %<input id="osSp" type="number"></label></div><div class="os-row"><b>C · Circulation（循环）</b><select id="osC"><option>稳定</option><option>灌注可疑</option><option>休克/无脉</option></select><label>BP mmHg<input id="osBP" type="number"></label></div><div class="os-row"><b>D · Disability（神经）</b><select id="osD"><option>清醒</option><option>意识改变</option><option>抽搐/昏迷</option></select><label>Glucose（血糖）mmol/L<input id="osGlu" type="number"></label></div><div class="os-row"><b>E · Exposure（全身）</b><select id="osE"><option>无明显异常</option><option>创伤/出血</option><option>中毒/高热/低温</option></select><label>Temp ℃<input id="osTemp" type="number"></label></div><div class="os-row"><b>Immediate Risks（立即风险）</b><label>K mmol/L<input id="osErK" type="number" step=".1"></label><label>Lactate mmol/L<input id="osLac" type="number" step=".1"></label><label>UOP mL/kg/h<input id="osUop" type="number" step=".1"></label></div></div><button class="primary" id="osABCDE" style="margin-top:10px">Run Triage（立即分诊）</button><div id="osABCDEOut"></div></div>
      <div class="os-grid"><div class="card"><h3>Resuscitation Checklist（复苏清单）</h3><div id="osResus"></div></div><div class="card"><h3>Fluid Safety（液体安全）</h3><div id="osFluidSafety"></div></div></div>
      <div class="card"><h3>Emergency Notes（急诊记录）</h3><textarea id="osErNote" placeholder="记录关键时间点、通路、ECG、POCUS、处置与复评结果"></textarea><button class="primary" id="osErSaveNote">保存到 Timeline（时间轴）</button></div>`;
    main.insertBefore(er,main.children[1]||null);
    document.querySelectorAll('[data-os-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.osGo)));
    bind();
  }
  function renderPatient(){const p=patient();$('osPatient').innerHTML=`<b>${esc(ptxt())}</b><div class="os-muted">主诉：${esc(p.chief||'未记录')} · 诊断：${esc(p.diagnosis||'未记录')}</div>`;$('osKpis').innerHTML=[['Cr',p.creatinine??'—'],['K',p.potassium??'—'],['Na',p.sodium??'—'],['Alb',p.albumin??'—'],['当前用药',p.currentMeds?'已记录':'—']].map(x=>`<div class="os-kpi"><span class="os-muted">${x[0]}</span><br><b>${esc(x[1])}</b></div>`).join('');}
  function risks(){const p=patient(),r=[];if(p.potassium>=6)r.push(['P0','K ≥ 6 mmol/L：高钾危重风险，结合 ECG/尿量/酸碱立即评估。']);else if(p.potassium>=5.5)r.push(['P1','K ≥ 5.5 mmol/L：高钾风险，结合趋势、ECG、尿量和病因。']);if(p.creatinine>4&&p.potassium>=5.5)r.push(['P0','肾功能异常 + 高钾：优先排除少尿/无尿与尿路梗阻。']);if(/呼吸困难|紫绀|严重喘/.test(p.chief||''))r.push(['P0','主诉提示呼吸危重：优先氧合、气道、胸部 POCUS/影像。']);if(/尿闭|无尿/.test(p.chief||''))r.push(['P0','尿闭/无尿：优先膀胱/尿道、K、酸碱与肾功能评估。']);if(/抽搐|昏迷/.test(p.chief||''))r.push(['P0','神经危重：优先气道/氧合/血糖/体温并控制持续发作。']);return r;}
  function renderRisks(){const r=risks();$('osCritical').innerHTML=r.length?`<div class="os-critical">${r.map(x=>`<div><span class="os-chip os-red">${x[0]}</span>${esc(x[1])}</div>`).join('')}</div>`:'<div class="os-note">当前 Patient State 未触发内置红旗。阴性结果不代表患者无风险。</div>';if($('osErCritical'))$('osErCritical').innerHTML=r.length?`<div class="os-critical">${r.map(x=>`<div>${esc(x[1])}</div>`).join('')}</div>`:'';}
  function renderProblems(){const p=state.problemList; if(!$('osProblems'))return;$('osProblems').innerHTML=p.length?`<div class="os-list">${p.slice().reverse().map((x,i)=>`<div class="os-row"><span class="os-chip ${x.priority==='P0'?'os-red':x.priority==='P1'?'os-amber':x.priority==='P2'?'os-yellow':'os-green'}">${esc(x.priority)}</span><b>${esc(x.text)}</b><small> · ${new Date(x.time).toLocaleString()}</small><button style="float:right" data-del-problem="${state.problemList.length-1-i}">删除</button></div>`).join('')}</div>`:'<div class="os-muted">暂无问题。建议至少建立 1 个 Problem List（临床问题列表）。</div>';document.querySelectorAll('[data-del-problem]').forEach(b=>b.onclick=()=>{state.problemList.splice(Number(b.dataset.delProblem),1);save();audit('delete_problem',b.dataset.delProblem);renderAll()});}
  function addProblem(){const t=$('osProblemText').value.trim();if(!t)return;state.problemList.push({text:t,priority:$('osProblemPri').value,time:now()});save();audit('add_problem',t);$('osProblemText').value='';renderAll();}
  function nextTests(){const p=patient(),chief=(p.chief||'').toLowerCase(),out=[];if(/呼吸困难|喘|紫绀/.test(chief))out.push(['P0','SpO₂/血气 + 胸部 POCUS（床旁超声）/影像','确认氧合与肺/胸膜病因']);if(/尿闭|无尿/.test(chief)||p.potassium>=5.5)out.push(['P0','ECG + K/血气 + 膀胱/尿路评估','高钾与梗阻是时间敏感问题']);if(/黄疸|黄/.test(chief))out.push(['P1','CBC + 生化/胆红素 + 腹部超声','区分溶血、肝细胞损伤、胆汁淤积/梗阻']);if(/呕吐|腹泻/.test(chief))out.push(['P1','CBC/生化/电解质 + POCUS/影像（按病史）','评估脱水、电解质和腹腔病变']);if(p.creatinine>2)out.push(['P1','尿检/尿比重 + UOP + 电解质趋势','区分肾前性、肾性及梗阻并动态评估']);if(!out.length)out.push(['P2','补齐完整病史 + 体格检查 + 基础 CBC/生化/尿检（按适应证）','当前信息不足以确定最有价值检查']);return out;}
  function renderNBT(){$('osNBT').innerHTML=nextTests().map(x=>`<div class="os-row"><span class="os-chip ${x[0]==='P0'?'os-red':x[0]==='P1'?'os-amber':'os-yellow'}">${x[0]}</span><b>${esc(x[1])}</b><div class="os-muted">为什么：${esc(x[2])}</div></div>`).join('');}
  function drugSafety(){const p=patient(),s=p.currentMeds||'',r=[];if(/美洛昔康|卡洛芬|罗贝考昔/.test(s)&&/泼尼松|地塞米松|甲泼尼龙/.test(s))r.push('NSAID + glucocorticoid（NSAID + 糖皮质激素）：胃肠道/肾脏风险需复核。');if(/美洛昔康|卡洛芬|罗贝考昔/.test(s)&&/阿米卡星|庆大霉素|妥布霉素/.test(s))r.push('NSAID + aminoglycoside（氨基糖苷类）：肾毒性风险需重点监测。');if(/依那普利|贝那普利|替米沙坦/.test(s)&&p.potassium>=5.5)r.push('RAAS inhibitor（RAAS抑制剂）+ 高钾：复核 K、肾功能和容量状态。');if(/螺内酯/.test(s)&&p.potassium>=5.5)r.push('Spironolactone（螺内酯）+ 高钾：高钾风险增加。');if(/地高辛/.test(s)&&p.potassium!=null&&p.potassium<3)r.push('Digoxin（地高辛）+ 低钾：毒性风险增加，需监测电解质。');if(/阿米卡星|庆大霉素|妥布霉素/.test(s)&&p.creatinine>2)r.push('Aminoglycoside（氨基糖苷类）+ 肾功能异常：复核适应证、剂量和监测。');return r;}
  function renderDrug(){const r=drugSafety();$('osDrugSafety').innerHTML=r.length?`<div class="os-list">${r.map(x=>`<div class="os-warning">⚠ ${esc(x)}</div>`).join('')}</div><p class="muted">这里只做规则提示，不替代具体制剂标签、剂量核验和实时监测。</p>`:'<div class="os-note">当前用药 + Patient State 未触发内置组合规则。</div>'}
  function renderTimeline(){const a=state.timeline.slice(-30).reverse();$('osTimeline').innerHTML=a.length?a.map(x=>`<div class="os-event"><b>${esc(new Date(x.time).toLocaleString())}</b> <span class="os-chip os-blue">${esc(x.type)}</span><div>${esc(x.text)}</div></div>`).join(''):'<div class="os-muted">暂无事件。</div>';}
  function addEvent(text,type){if(!text)return;state.timeline.push({time:now(),type,text,patientId:patient().patientId||''});state.timeline=state.timeline.slice(-300);save();audit('add_timeline',type+':'+text);renderTimeline();}
  function reassess(){const type=$('osReassessType').value;const maps={
    'Shock / Perfusion（休克/灌注）':['HR/BP（心率/血压）','CRT + pulse quality（CRT/脉搏质量）','Mentation（意识）','Lactate trend（乳酸趋势）','UOP（尿量）','Temperature（体温）','Fluid tolerance（液体耐受性）'],
    'Respiratory（呼吸）':['RR/effort（呼吸频率/呼吸功）','SpO₂ ± blood gas（SpO₂/血气）','Airway（气道）','Lung sounds/POCUS（肺音/床旁超声）','Oxygen requirement（氧需求）'],
    'AKI / Fluid（肾损伤/液体）':['Weight trend（体重趋势）','UOP（尿量）','Creatinine/K/Na trend（Cr/K/Na趋势）','Fluid balance（液体平衡）','Edema/RR（水肿/呼吸频率）','Blood pressure（血压）'],
    'Pain（疼痛）':['Pain score（疼痛评分）','HR/RR/BP（生命体征）','Sedation（镇静程度）','Mobility/interaction（活动与互动）','Adverse effects（不良反应）'],
    'General（综合）':['Vitals（生命体征）','Perfusion（灌注）','Pain（疼痛）','GI intake/output（摄入/排出）','UOP（尿量）','Labs trend（检验趋势）','Treatment response（治疗反应）']};$('osReassessOut').innerHTML=`<div class="os-list">${maps[type].map(x=>`<label class="os-row"><input type="checkbox"> ${esc(x)}</label>`).join('')}</div><div class="os-warning">复评不是“做完治疗就结束”，而是判断治疗是否达到目标，并决定继续、调整或升级。</div>`;addEvent('生成复评清单：'+type,'复评');}
  function snapshots(){const p=patient(),key='vct50_monitor_snapshots_v2',all=safeParse(localStorage.getItem(key),{}),id=p.patientId||'__unidentified__';return {key,all,id,arr:all[id]||[]};}
  function snapshot(){const x=snapshots();x.arr.push({time:now(),weight:pnum(patient().weight),creatinine:pnum(patient().creatinine),potassium:pnum(patient().potassium),sodium:pnum(patient().sodium),albumin:pnum(patient().albumin)});x.all[x.id]=x.arr.slice(-100);localStorage.setItem(x.key,JSON.stringify(x.all));addEvent('记录 Patient State 快照','监测');renderTrend();}
  function pnum(x){const n=Number(x);return Number.isFinite(n)?n:null}
  function renderTrend(){const x=snapshots(),a=x.arr;if(!a.length){$('osTrend').innerHTML='<div class="os-muted">暂无快照。</div>';return}const last=a[a.length-1],prev=a[a.length-2];const ks=[['weight','kg'],['creatinine','mg/dL'],['potassium','mmol/L'],['sodium','mmol/L'],['albumin','g/dL']];$('osTrend').innerHTML=`<div class="os-muted">${a.length} snapshots（快照） · ${new Date(last.time).toLocaleString()}</div><table class="os-table"><thead><tr><th>指标</th><th>最新</th><th>上次</th><th>变化</th></tr></thead><tbody>${ks.map(k=>{const v=last[k[0]],q=prev?.[k[0]],d=v!=null&&q!=null?v-q:null;return `<tr><td>${k[0]} <small>${k[1]}</small></td><td>${v??'—'}</td><td>${q??'—'}</td><td>${d==null?'—':(d>0?'+':'')+d.toFixed(2)}</td></tr>`}).join('')}</tbody></table>`}
  function tasks(){if(!$('osTasks'))return;$('osTasks').innerHTML=state.tasks.length?state.tasks.slice().reverse().map((x,i)=>`<div class="os-row"><label><input type="checkbox" ${x.done?'checked':''} data-task="${state.tasks.length-1-i}"> ${esc(x.text)}</label><small> ${new Date(x.time).toLocaleString()}</small></div>`).join(''):'<div class="os-muted">暂无任务。</div>';document.querySelectorAll('[data-task]').forEach(c=>c.onchange=()=>{state.tasks[Number(c.dataset.task)].done=c.checked;save();audit('task_update',c.dataset.task);});}
  function addTask(){const t=$('osTaskText').value.trim();if(!t)return;state.tasks.push({text:t,time:now(),done:false});save();audit('add_task',t);$('osTaskText').value='';tasks();}
  function pomr(){const p=patient();$('osPOMR').innerHTML=state.problemList.length?state.problemList.map(x=>`<div class="os-row"><b>${esc(x.priority)} · ${esc(x.text)}</b><div class="os-grid"><div><small>Assessment（评估）</small><p>${esc(p.diagnosis||'待补充证据')}</p></div><div><small>Plan（计划）</small><p>补充支持/反对证据；选择下一项最有价值检查；设定治疗目标与复评时间。</p></div></div></div>`).join(''):'<div class="os-muted">先建立 Problem List。</div>';}
  function fluidSafety(){const p=patient(),f=[];if(p.creatinine>4)f.push('Cr > 4 mg/dL：液体方案必须结合尿量、灌注和液体过负荷风险动态调整。');if(/心衰|CHF|HCM|肺水肿/.test((p.conditions||'')+' '+(p.diagnosis||'')))f.push('心脏疾病/肺水肿风险：避免仅按固定公式持续加液，重点动态复评。');if(p.albumin<2.5)f.push('低白蛋白：注意水肿/第三间隙与液体耐受性。');return f}
  function renderFluidSafety(){const f=fluidSafety();$('osFluidSafety').innerHTML=f.length?f.map(x=>`<div class="os-warning">⚠ ${esc(x)}</div>`).join(''):'<div class="os-note">当前 Patient State 未触发本模块的液体安全规则。</div>'}
  function triage(){const vals=['osA','osB','osC','osD','osE'].map(id=>$(id).value),red=vals.filter(x=>/阻塞|无法|严重|紫绀|休克|无脉|抽搐|昏迷/.test(x));const k=pnum($('osErK').value),sp=pnum($('osSp').value),glu=pnum($('osGlu').value),u=pnum($('osUop').value);if(k>=6)red.push('K ≥ 6');if(sp!=null&&sp<90)red.push('SpO₂ < 90%');if(glu!=null&&glu<3.3)red.push('Glucose < 3.3 mmol/L（≈60 mg/dL）');if(u===0)red.push('UOP = 0');const pri=red.length?'P0 · Immediate Stabilization（立即稳定生命）':'P1/P2 · Rapid Assessment（快速评估）';$('osABCDEOut').innerHTML=`<div class="${red.length?'os-critical':'os-note'}"><b>${pri}</b><div>${red.length?red.map(esc).join(' · '):'未触发本工具基础红旗。仍需完整体检与动态监测。'}</div></div><div class="os-warning">A→B→C→D→E；生命支持与病因检查并行。阈值是筛查提示，不替代物种/实验室参考区间和临床判断。</div>`;renderResus(red);addEvent('ABCDE 分诊：'+pri,'急诊');}
  function renderResus(red=[]){const items=['确认气道/氧合','ECG + BP + SpO₂ + 温度','建立 IV/IO 通路（按需）','床旁血糖/血气/乳酸（按适应证）','采样后尽快启动必要治疗','记录初始时间点并设定复评时间','避免未经评估的过量液体/药物'];$('osResus').innerHTML=items.map(x=>`<label class="os-row"><input type="checkbox"> ${esc(x)}</label>`).join('')+(red.length?`<div class="os-critical">当前红旗：${red.map(esc).join('、')}</div>`:'');}
  let timerStart=null,timerElapsed=0,timerId=null;
  function timerRender(){const sec=Math.floor((timerElapsed+(timerStart?Date.now()-timerStart:0))/1000),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');if($('osErTimer'))$('osErTimer').textContent=`${m}:${s}`;}
  function startTimer(){if(timerStart)return;timerStart=Date.now();timerId=setInterval(timerRender,250);audit('emergency_timer','start');}
  function stopTimer(){if(!timerStart)return;timerElapsed+=Date.now()-timerStart;timerStart=null;clearInterval(timerId);timerId=null;timerRender();audit('emergency_timer','stop');}
  function resetTimer(){stopTimer();timerElapsed=0;timerRender();audit('emergency_timer','reset');}
  function saveErNote(){const t=$('osErNote').value.trim();if(!t)return;addEvent(t,'急诊记录');$('osErNote').value='';}
  function copyContext(){const p=patient(),ctx={version:'5.0-r08',patient:p,problems:state.problemList,timeline:state.timeline.slice(-50),tasks:state.tasks,labs:state.labs,vitals:state.vitals,goals:state.goals,risks:risks(),next_best_tests:nextTests(),drug_safety:drugSafety(),fluid_safety:fluidSafety()};const text=JSON.stringify(ctx,null,2);navigator.clipboard?.writeText(text);audit('copy_ai_context','clinical OS context');alert('AI Clinical Context 已复制。');}
  function exportOS(){const blob=new Blob([JSON.stringify({version:'5.0-r08',exported_at:now(),patient:patient(),state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`VCT50-r08-${patient().patientId||'patient'}-clinical-os.json`;a.click();URL.revokeObjectURL(a.href);audit('export_state','clinical os');}
  function renderAll(){renderPatient();renderRisks();renderProblems();renderNBT();renderDrug();renderTimeline();renderTrend();tasks();pomr();renderFluidSafety();renderAIDifferentials();}
  function renderAIDifferentials(){const el=$('osAIDifferentials');if(!el)return;const a=Array.isArray(state.differentials)?state.differentials:[];el.innerHTML=a.length?a.slice(-30).map(x=>`<div class="os-row"><span class="os-chip os-yellow">${esc(x.priority||'P2')}</span><b>${esc(x.text||x.name||x.label||'')}</b><div class="os-muted">Suggested（AI建议） · ${esc(x.detail||'需结合检查与复评')}</div></div>`).join(''):'<div class="os-note">暂无 AI 鉴别诊断建议。</div>'}
  function bind(){
    $('osAddProblem').onclick=addProblem;$('osAddEvent').onclick=()=>{const t=$('osEventText').value.trim();addEvent(t,$('osEventType').value);$('osEventText').value=''};$('osReassess').onclick=reassess;$('osSnapshot').onclick=snapshot;$('osAddTask').onclick=addTask;$('osCopyContext').onclick=copyContext;$('osExport').onclick=exportOS;
    $('osABCDE').onclick=triage;$('osErStart').onclick=startTimer;$('osErStop').onclick=stopTimer;$('osErReset').onclick=resetTimer;$('osErSaveNote').onclick=saveErNote;
    document.addEventListener('vct50:patient-change',()=>{renderAll();if($('osErK'))$('osErK').value=patient().potassium??''});
    renderAll();if($('osErK'))$('osErK').value=patient().potassium??'';timerRender();
  }
  load();
  try{ if(!window.VCT50_PATIENT_STATE){ const p=safeParse(localStorage.getItem('vct50_patient_state'),null); if(p&&typeof p==='object') window.VCT50_PATIENT_STATE=p; } }catch{}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
  window.VCT50_CLINICAL_OS={state,renderAll,addEvent,risks,nextTests,drugSafety,fluidSafety,copyContext};
})();
