"use strict";
(function(){
const $=id=>document.getElementById(id); const num=id=>{const x=parseFloat($(id)?.value);return Number.isFinite(x)?x:null};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function triage(){const vals=[$('qAir').value,$('qBreath').value,$('qCirc').value,$('qNeuro').value];let level='常规优先级',why=[];if(vals.some(x=>/阻塞|无脉|休克|严重|抽搐|昏迷/.test(x))){level='立即处理 / ABC优先';why=['存在至少一个生命支持红旗'];}else if(vals.some(x=>/可疑|增加|灌注可疑|意识改变/.test(x))){level='高优先级';why=['存在潜在失代偿迹象'];}else why=['当前输入未触发本工具红旗'];$('qTriageOut').innerHTML=`<div class="${level.includes('立即')?'bad':level.includes('高')?'warn':'result'}"><b>${level}</b><br>${why.join('；')}<br>建议顺序：气道 → 呼吸/氧合 → 循环/灌注 → 神经状态 → 进一步诊断。</div>`}
function corrCa(){const ca=num('qCa'),alb=num('qAlb');if(ca===null||alb===null)return $('qCaOut').innerHTML='<div class="bad">请输入总钙和白蛋白。</div>';const c=ca+0.8*(4-alb);$('qCaOut').innerHTML=`<div class="result">校正总钙 ≈ <b>${c.toFixed(2)} mg/dL</b>（简化公式：Ca + 0.8×(4−Alb)）。</div>`}
function fena(){const un=num('qUNa'),sn=num('qSNa'),ucr=num('qUCr'),scr=num('qSCr');if([un,sn,ucr,scr].some(x=>x===null||x<=0))return $('qFenaOut').innerHTML='<div class="bad">请输入四项有效数据。</div>';const f=100*(un*scr)/(sn*ucr);$('qFenaOut').innerHTML=`<div class="result">FENa ≈ <b>${f.toFixed(2)}%</b>。</div>`}
function balance(){const i=num('qIn'),u=num('qUr'),l=num('qLoss')||0,w=num('qW');if(i===null||u===null||w===null||w<=0)return $('qBalanceOut').innerHTML='<div class="bad">请输入输入量、尿量和体重。</div>';const net=i-u-l; $('qBalanceOut').innerHTML=`<div class="result">净液体平衡：<b>${net.toFixed(0)} mL</b>；按体重：<b>${(net/w).toFixed(1)} mL/kg</b>。</div><div class="info">应结合多个时间点、体重趋势、胸腹腔积液、肺部影像/POCUS、血压和肾功能解释，不能只看单次净平衡。</div>`}
function oxy(){const s=num('qSpo2'),f=num('qFio2'),rr=num('qRR');if(s===null||f===null)return $('qOxyOut').innerHTML='<div class="bad">请输入SpO₂和FiO₂。</div>';const sf=s/(f/100);$('qOxyOut').innerHTML=`<div class="result">SpO₂/FiO₂ ≈ <b>${sf.toFixed(0)}</b>；RR：${rr??'未记录'}/min。</div><div class="info">仅用于趋势记录，不能替代PaO₂/血气、临床呼吸功和影像评估。</div>`}
function snapshot(){const ids=['patientSpecies','patientBreed','patientWeight','caseId','caseSpecies','caseBreed','caseAge','caseSex','caseWeight','caseChief','caseHistory','casePast','casePrevent','caseTests','caseResults','caseDx','caseDDx','casePlan','caseAdvice','caseFollow'];const o={exported_at:new Date().toISOString(),version:'5.0-r08',fields:{}};ids.forEach(id=>{if($(id))o.fields[id]=$(id).value});try{o.timeline=JSON.parse(localStorage.getItem('vct50_timeline')||'[]')}catch{o.timeline=[]}const blob=new Blob([JSON.stringify(o,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(o.fields.caseId||'vet-case')+'-snapshot-5.0.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('qSnapshotOut').innerHTML='<div class="good">病例快照已生成。</div>'}
function wire(){[['qTriageBtn',triage],['qCaBtn',corrCa],['qFenaBtn',fena],['qBalanceBtn',balance],['qOxyBtn',oxy],['qSnapshotBtn',snapshot]].forEach(([id,fn])=>$(id)?.addEventListener('click',fn))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
