"use strict";
/* Vet Clinical Toolbox 5.0-r08 · Clinical Core 2.0
 * Unified patient dashboard, emergency triage, red flags, lab pattern engine,
 * drug/fluid safety audit, monitoring trends, anesthesia risk, structured imaging templates.
 * Decision-support only; never replaces clinician judgment or product labeling.
 */
(function(){
  const $=id=>document.getElementById(id), n=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:null};
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
  const getP=()=>window.VCT50_PATIENT_STATE||{};
  const out=(id,html)=>{if($(id))$(id).innerHTML=html};
  const PKEY="vct50_monitoring_v2";
  function ptxt(){const p=getP();return `${p.patientId||"未建档"} · ${p.species||""} · ${p.weight?`${p.weight} kg`:"体重未录入"}`}
  function go(v){const b=document.querySelector(`nav button[data-v="${v}"]`);b?.click();window.scrollTo({top:0,behavior:"smooth"})}
  function inject(){
    if(!$('vct-core-style')){const st=document.createElement('style');st.id='vct-core-style';st.textContent=`
      .core-dashboard{display:grid;grid-template-columns:1.35fr .85fr;gap:12px}.core-stat{font-size:22px;font-weight:800}.core-kpi{border:1px solid var(--line);border-radius:12px;padding:10px;background:#fff}.core-actions{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px}.core-actions button{min-height:54px}.critical-banner{border:2px solid #dc2626;background:#fff1f2;color:#991b1b;border-radius:12px;padding:12px;font-weight:700}.triage-grid{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:8px}.triage-box{border:1px solid var(--line);border-radius:10px;padding:10px}.triage-box.red{border-color:#fca5a5;background:#fff1f2}.triage-box.amber{border-color:#fcd34d;background:#fffbeb}.monitor-table input{min-width:90px}.trend{height:10px;border-radius:99px;background:#e5e7eb;overflow:hidden}.trend>i{display:block;height:100%;background:var(--p)}.score{font-size:28px;font-weight:900}.priority{display:inline-block;border-radius:999px;padding:4px 9px;font-size:11px;font-weight:800}.p0{background:#fee2e2;color:#991b1b}.p1{background:#ffedd5;color:#9a3412}.p2{background:#fef3c7;color:#92400e}.p3{background:#dcfce7;color:#166534}.core-report{white-space:pre-wrap;background:#f7faf9;padding:12px;border-radius:10px}.img-grid{display:grid;grid-template-columns:repeat(3,minmax(180px,1fr));gap:8px}.checkrow{display:flex;align-items:center;gap:8px;padding:7px;border-bottom:1px solid var(--line)}.checkrow input{width:auto}.sticky-tools{position:sticky;bottom:10px;z-index:20;background:#ffffffee;border:1px solid var(--line);padding:8px;border-radius:12px;backdrop-filter:blur(6px)}
      @media(max-width:800px){.core-dashboard{grid-template-columns:1fr}.triage-grid{grid-template-columns:repeat(2,1fr)}.img-grid{grid-template-columns:1fr}}
    `;document.head.appendChild(st)}
    if($('coreDashboard'))return;
    const nav=$('nav'); if(nav){const b=document.createElement('button');b.dataset.v='coreDashboard';b.textContent='🧠 临床总览';b.onclick=()=>window.show?.('coreDashboard');nav.insertBefore(b,nav.children[1]||null);const e=document.createElement('button');e.dataset.v='coreEmergency';e.textContent='🚨 急诊驾驶舱';e.onclick=()=>window.show?.('coreEmergency');nav.insertBefore(e,nav.children[2]||null)}
    const main=document.querySelector('main');
    const dash=document.createElement('section');dash.id='coreDashboard';dash.className='view';dash.innerHTML=`
      <div class="card"><h2>🧠 临床总览 · Patient State 2.0</h2><p class="muted">当前患者是全系统上下文。任何计算、风险审核和临床判断都应先看患者状态，再看单个工具结果。</p><div id="coreCritical"></div></div>
      <div class="core-dashboard"><div class="card"><h3 id="corePatientTitle">当前患者</h3><div class="grid" id="coreKpis"></div><h3>当前问题</h3><div id="coreProblems" class="grid"></div></div>
      <div class="card"><h3>⚡ 快速入口</h3><div class="core-actions"><button class="primary" data-core-go="coreEmergency">🚨 急诊</button><button class="secondary" data-core-go="clinical">🔎 临床决策</button><button class="secondary" data-core-go="fluid">💧 液体</button><button class="secondary" data-core-go="dose">💊 剂量</button><button class="secondary" data-core-go="anesthesia">😴 麻醉</button><button class="secondary" data-core-go="emergency">❤️ CPR</button><button class="secondary" data-core-go="cbc">🧪 CBC</button><button class="secondary" data-core-go="ai">🤖 AI</button></div><div class="sticky-tools" style="margin-top:12px"><button class="primary" id="coreSync">同步患者并重新评估</button></div></div></div>
      <div class="card"><h3>💊 当前用药安全</h3><div id="coreDrugAudit"></div></div>
      <div class="card"><h3>📈 住院监测趋势</h3><div id="coreTrendOut"></div><div class="toolbar"><button class="secondary" id="coreAddTrend">记录当前快照</button><button class="secondary" id="coreClearTrend">清除当前患者趋势</button></div></div>`;
    main.insertBefore(dash,main.firstChild);
    const er=document.createElement('section');er.id='coreEmergency';er.className='view';er.innerHTML=`
      <div class="card"><h2>🚨 急诊驾驶舱</h2><p class="muted">原则：先处理最危及生命的问题，再继续诊断。红旗是触发进一步评估/立即行动的提示，不是自动诊断。citeturn0search10</p><div id="erCritical"></div></div>
      <div class="card"><h3>ABCDE 快速分诊</h3><div class="triage-grid">
        <div class="triage-box"><b>A · Airway</b><select id="erA"><option>通畅</option><option>可疑</option><option>阻塞/无法维持</option></select></div>
        <div class="triage-box"><b>B · Breathing</b><select id="erB"><option>稳定</option><option>呼吸功增加</option><option>严重呼吸窘迫/紫绀</option></select></div>
        <div class="triage-box"><b>C · Circulation</b><select id="erC"><option>稳定</option><option>灌注可疑</option><option>休克/无脉</option></select></div>
        <div class="triage-box"><b>D · Disability</b><select id="erD"><option>清醒</option><option>意识改变</option><option>抽搐/昏迷</option></select></div>
        <div class="triage-box"><b>E · Exposure</b><select id="erE"><option>无明显异常</option><option>创伤/出血</option><option>中毒/高热/低温</option></select></div></div><button class="primary" id="erAssess" style="margin-top:10px">立即分诊</button><div id="erOut"></div></div>
      <div class="grid"><div class="card"><h3>⚡ 高钾红旗</h3><label>K mmol/L<input id="erK" type="number" step=".1"></label><label>心率 bpm<input id="erHR" type="number"></label><label>尿量<select id="erUop"><option>正常/未知</option><option>减少</option><option>无尿</option></select></label><button class="primary" id="erKBtn">评估</button><div id="erKOut"></div></div>
      <div class="card"><h3>🩸 低血糖</h3><label>血糖 mg/dL<input id="erGlu" type="number"></label><label>意识<select id="erMent"><option>正常</option><option>异常</option><option>抽搐/昏迷</option></select></label><button class="primary" id="erGluBtn">评估</button><div id="erGluOut"></div></div>
      <div class="card"><h3>🫁 呼吸危重度</h3><label>SpO₂ %<input id="erSp" type="number"></label><label>呼吸频率<input id="erRR" type="number"></label><label>呼吸功<select id="erWork"><option>轻</option><option>中</option><option>重</option></select></label><button class="primary" id="erRespBtn">评估</button><div id="erRespOut"></div></div>
      <div class="card"><h3>🧠 癫痫持续状态</h3><label>持续时间 min<input id="erSeiz" type="number"></label><label>是否反复且未恢复意识<select id="erRec"><option>否</option><option>是</option></select></label><button class="primary" id="erSeizBtn">评估</button><div id="erSeizOut"></div></div></div>
      <div class="card"><h3>❤️ CPR 快速检查</h3><div class="result">进入现有「急救/CPR」模块执行 RECOVER 流程；2024 RECOVER BLS/ALS/监测指南已更新，2026 年又发布了犬猫 First Aid 指南。citeturn0search0turn0search1</div><button class="primary" data-core-go="emergency">打开 CPR 模块</button></div>
      <div class="card"><h3>💧 复苏液体安全</h3><div id="erFluidOut"></div><button class="secondary" data-core-go="fluid">打开液体模块</button></div>`;
    main.insertBefore(er,main.children[1]||null);
    document.querySelectorAll('[data-core-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.coreGo)));
    $('coreSync').onclick=()=>{document.querySelector('#syncPatientBtn')?.click();setTimeout(renderAll,50)};
    $('coreAddTrend').onclick=addTrend;$('coreClearTrend').onclick=clearTrend;
    $('erAssess').onclick=assessABCDE;$('erKBtn').onclick=assessK;$('erGluBtn').onclick=assessGlu;$('erRespBtn').onclick=assessResp;$('erSeizBtn').onclick=assessSeiz;
  }
  function problems(){const p=getP(),x=[];if(p.potassium!==null&&p.potassium!==undefined){if(p.potassium>=6)x.push(["高钾","p0"]);else if(p.potassium>=5.5)x.push(["高钾风险","p1"]);else if(p.potassium<3)x.push(["低钾","p1"])}if(p.creatinine!=null&&p.creatinine>2)x.push(["肾功能异常","p1"]);if(p.albumin!=null&&p.albumin<2.5)x.push(["低白蛋白","p1"]);if((p.chief||"").match(/呼吸困难|紫绀|喘|呼吸急促/))x.push(["呼吸问题","p0"]);if((p.chief||"").match(/尿闭|无尿/))x.push(["尿路急症","p0"]);if((p.chief||"").match(/抽搐|昏迷/))x.push(["神经急症","p0"]);return x}
  function drugAudit(){const p=getP(),m=(p.currentMeds||"").split(/[，,；;\n]+/).map(x=>x.trim()).filter(Boolean);const s=m.join(" ");const hits=[];if(/美洛昔康/.test(s)&&/泼尼松|地塞米松|甲泼尼龙/.test(s))hits.push("NSAID + 糖皮质激素：胃肠道/肾脏风险升高，需复核是否必要并监测。");if(/美洛昔康|卡洛芬|罗贝考昔/.test(s)&&/阿米卡星|庆大霉素|妥布霉素/.test(s))hits.push("NSAID + 氨基糖苷类：肾毒性风险需重点监测。");if(/依那普利|贝那普利|替米沙坦/.test(s)&&p.potassium>=5.5)hits.push("RAAS抑制剂 + 当前高钾：需复核K、肾功能和容量状态。");if(/螺内酯/.test(s)&&p.potassium>=5.5)hits.push("螺内酯 + 当前高钾：高钾风险增加。");if(/地高辛/.test(s)&&p.potassium!==null&&p.potassium<3)hits.push("低钾可增加地高辛毒性风险；应纠正电解质并监测。");if(/阿米卡星|庆大霉素|妥布霉素/.test(s)&&p.creatinine>2)hits.push("氨基糖苷类 + 肾功能异常：肾毒性风险，需核对适应证、剂量与监测。");return hits}
  function renderDashboard(){const p=getP(),ps=problems(),audit=drugAudit();$('corePatientTitle').textContent=`当前患者 · ${ptxt()}`;$('coreKpis').innerHTML=[['体重',p.weight?`${p.weight} kg`:'—'],['肌酐',p.creatinine??'—'],['K',p.potassium??'—'],['Na',p.sodium??'—'],['Alb',p.albumin??'—'],['诊断',p.diagnosis||'—']].map(x=>`<div class="core-kpi"><div class="muted">${x[0]}</div><div class="core-stat">${esc(x[1])}</div></div>`).join('');$('coreProblems').innerHTML=ps.length?ps.map(x=>`<div class="core-kpi"><span class="priority ${x[1]}">${x[1]==='p0'?'立即处理':x[1]==='p1'?'高优先级':'常规'}</span><div style="margin-top:6px;font-weight:800">${esc(x[0])}</div></div>`).join(''):'<div class="good">当前 Patient State 未触发内置高优先级红旗；这不代表患者无风险。</div>';$('coreDrugAudit').innerHTML=audit.length?audit.map(x=>`<div class="bad">⚠️ ${esc(x)}</div>`).join(''):'<div class="good">当前用药 + Patient State 未触发内置高风险组合规则；仍需核对具体制剂标签、剂量、疗程与禁忌证。</div>';renderTrend()}
  function criticalFromState(){const p=getP(),f=[];if(p.potassium>=6)f.push('K ≥ 6 mmol/L：高钾危重风险，结合ECG/尿量/酸碱状态立即评估。');else if(p.potassium>=5.5)f.push('K ≥ 5.5 mmol/L：高钾风险，需结合趋势、尿量和ECG。');if(p.creatinine>4&&p.potassium>=5.5)f.push('肾功能异常 + 高钾：优先排除少尿/无尿、尿路梗阻及严重AKI。');if((p.chief||'').match(/呼吸困难|紫绀/))f.push('主诉提示呼吸危重：优先评估气道、呼吸、SpO₂/血气和胸部影像/POCUS。');if((p.chief||'').match(/尿闭|无尿/))f.push('尿闭/无尿：优先评估膀胱、尿道阻塞、K和酸碱状态。');return f}
  function renderCritical(){const f=criticalFromState();$('coreCritical').innerHTML=f.length?`<div class="critical-banner">${f.map(x=>`<div>🔴 ${esc(x)}</div>`).join('')}</div>`:'<div class="good">Patient State 当前未触发内置 Critical 规则。急诊患者仍应按 ABCDE 分诊。</div>';if($('erCritical'))$('erCritical').innerHTML=f.length?`<div class="critical-banner">${f.map(x=>`<div>🔴 ${esc(x)}</div>`).join('')}</div>`:''}
  function assessABCDE(){const vals=['erA','erB','erC','erD','erE'].map(id=>$(id).value);const red=vals.filter(x=>/阻塞|无法|严重|紫绀|休克|无脉|抽搐|昏迷/.test(x));const amber=vals.filter(x=>/可疑|增加|灌注|意识|创伤|中毒|高热|低温/.test(x));const cls=red.length?'bad':amber.length?'warn':'good';const pri=red.length?'P0 · 立即稳定生命':amber.length?'P1 · 快速补充评估':'P2 · 常规初筛';out('erOut',`<div class="${cls}"><span class="score">${pri}</span><br>红旗 ${red.length} 项；警戒 ${amber.length} 项。</div><div class="info">处理顺序：A→B→C→D→E，同时建立监测、静脉/骨内通路（按需）并寻找可逆病因。</div>`)}
  function assessK(){const k=n('erK'),hr=n('erHR'),u=$('erUop').value;const f=[];if(k!==null&&k>=6)f.push('K ≥ 6');if(k!==null&&k>=5.5)f.push('K ≥ 5.5');if(u==='无尿')f.push('无尿');if(hr!==null&&hr<80)f.push('相对心动过缓');out('erKOut',`<div class="${f.length?'bad':'good'}">${f.length?'🔴 '+f.join(' + ')+'：立即ECG/酸碱/肾功能与尿路评估。':'当前输入未触发内置高钾红旗。'}</div><div class="warn">不要仅凭血钾数字决定治疗；高钾处置取决于ECG、酸碱、尿量、病因和趋势。</div>`)}
  function assessGlu(){const g=n('erGlu'),m=$('erMent').value;const red=(g!==null&&g<60)||/抽搐|昏迷/.test(m);out('erGluOut',`<div class="${red?'bad':'result'}">${red?'🔴 低血糖/神经危重风险：立即确认血糖、建立通路并按院内急救protocol处理。':'当前输入未触发本工具的危重阈值。'}</div><div class="info">猫、幼龄、胰岛素治疗、肝病和脓毒症患者需要结合病因判断，治疗后应复测趋势。</div>`)}
  function assessResp(){const sp=n('erSp'),rr=n('erRR'),w=$('erWork').value;const red=(sp!==null&&sp<90)||w==='重';const am=(sp!==null&&sp<94)||w==='中';out('erRespOut',`<div class="${red?'bad':am?'warn':'good'}">${red?'P0 · 呼吸危重':am?'P1 · 呼吸风险':'目前未触发基础红旗'}${sp!==null?`；SpO₂ ${sp}%`:''}${rr!==null?`；RR ${rr}`:''}</div><div class="info">先保证氧合和减少应激，再完成胸部POCUS/影像、血气等病因评估。</div>`)}
  function assessSeiz(){const t=n('erSeiz'),r=$('erRec').value;const red=(t!==null&&t>=5)||r==='是';out('erSeizOut',`<div class="${red?'bad':'result'}">${red?'🔴 高度警惕癫痫持续状态：立即保障气道/氧合、血糖、体温并按院内急救protocol控制持续抽搐。':'当前输入未触发本工具的危重阈值。'}</div><div class="info">持续抽搐属于时间敏感急症；控制发作与寻找代谢/中毒/结构性原因并行。</div>`)}
  function addTrend(){const p=getP();if(!p.patientId){alert('请先建立患者编号。');return}const all=JSON.parse(localStorage.getItem(PKEY)||'{}');const arr=all[p.patientId]||[];arr.push({time:new Date().toISOString(),weight:p.weight,creatinine:p.creatinine,potassium:p.potassium,sodium:p.sodium,albumin:p.albumin,diagnosis:p.diagnosis});all[p.patientId]=arr.slice(-50);localStorage.setItem(PKEY,JSON.stringify(all));renderTrend()}
  function clearTrend(){const p=getP();const all=JSON.parse(localStorage.getItem(PKEY)||'{}');if(p.patientId)delete all[p.patientId];localStorage.setItem(PKEY,JSON.stringify(all));renderTrend()}
  function renderTrend(){if(!$('coreTrendOut'))return;const p=getP(),all=JSON.parse(localStorage.getItem(PKEY)||'{}'),arr=p.patientId?(all[p.patientId]||[]):[];if(!arr.length){$('coreTrendOut').innerHTML='<div class="muted">暂无快照。同步患者后可记录趋势。</div>';return}const last=arr[arr.length-1],prev=arr[arr.length-2];const rows=['weight','creatinine','potassium','sodium','albumin'].map(k=>{const a=last[k],b=prev?.[k];let d=(a!=null&&b!=null)?a-b:null;return `<tr><td>${k}</td><td>${a??'—'}</td><td>${b??'—'}</td><td>${d==null?'—':(d>0?'+':'')+d.toFixed(2)}</td></tr>`}).join('');$('coreTrendOut').innerHTML=`<div class="muted">${arr.length} 个快照 · 最新 ${new Date(last.time).toLocaleString()}</div><table><thead><tr><th>指标</th><th>最新</th><th>上次</th><th>变化</th></tr></thead><tbody>${rows}</tbody></table>`}
  function labEngine(){
    const q=document.createElement('div');q.className='card';q.id='coreLabEngine';q.innerHTML=`<h3>🧪 综合实验室模式引擎</h3><p class="muted">使用本院/仪器参考区间时，请先按物种与实验室范围校正。下面是临床模式提示，不是诊断。</p><div class="grid"><div><label>HCT %<input id="ceHct" type="number"></label><label>Retic %<input id="ceRet" type="number"></label><label>WBC ×10⁹/L<input id="ceWbc" type="number"></label><label>NEU ×10⁹/L<input id="ceNeu" type="number"></label><label>PLT ×10⁹/L<input id="cePlt" type="number"></label></div><div><label>ALT U/L<input id="ceAlt" type="number"></label><label>ALP U/L<input id="ceAlp" type="number"></label><label>TBIL μmol/L<input id="ceTb" type="number"></label><label>CREA mg/dL<input id="ceCr" type="number"></label><label>K mmol/L<input id="ceK" type="number"></label></div><div><label>Glucose mg/dL<input id="ceGlu" type="number"></label><label>Na mmol/L<input id="ceNa" type="number"></label><label>Albumin g/dL<input id="ceAlb" type="number"></label><label>Lactate mmol/L<input id="ceLac" type="number"></label><button class="primary" id="ceRun">生成模式</button></div></div><div id="ceOut"></div>`;const c=$('clinical');c?.appendChild(q);$('ceRun').onclick=()=>{const a=[];const h=n('ceHct'),r=n('ceRet'),w=n('ceWbc'),neu=n('ceNeu'),plt=n('cePlt'),alt=n('ceAlt'),alp=n('ceAlp'),tb=n('ceTb'),cr=n('ceCr'),k=n('ceK'),glu=n('ceGlu'),na=n('ceNa'),alb=n('ceAlb'),lac=n('ceLac');if(h!==null&&h<25)a.push('贫血模式');if(h!==null&&h<25&&r!==null&&r>1.5)a.push('偏再生性贫血（需结合绝对网织红细胞）');if(h!==null&&h<25&&r!==null&&r<=1.5)a.push('偏非再生性贫血');if(w!==null&&w>20&&neu!==null&&neu>15)a.push('炎症/应激性白细胞模式');if(plt!==null&&plt<100)a.push('血小板减少模式，先排除EDTA聚集/假性减少');if(alt!==null&&alt>150)a.push('肝细胞损伤指标升高');if(alp!==null&&alp>200)a.push('胆汁淤积/诱导性酶升高模式');if(tb!==null&&tb>20)a.push('高胆红素血症');if(cr!==null&&cr>2)a.push('肾功能异常模式');if(k!==null&&k>=5.5)a.push('高钾红旗');if(glu!==null&&glu<60)a.push('低血糖红旗');if(na!==null&&na<140)a.push('低钠模式');if(na!==null&&na>160)a.push('高钠模式');if(alb!==null&&alb<2.5)a.push('低白蛋白');if(lac!==null&&lac>=4)a.push('高乳酸/灌注或代谢压力红旗');$('ceOut').innerHTML=a.length?a.map(x=>`<div class="${/红旗/.test(x)?'bad':'info'}">${esc(x)}</div>`).join(''):'<div class="good">未触发本模式引擎的预设条件。</div><div class="warn">必须结合物种、实验室参考区间、病史和趋势；单项异常不能作为最终诊断。</div>'}}
  function imaging(){const c=$('clinical');if(!c||$('coreImaging'))return;const q=document.createElement('div');q.className='card';q.id='coreImaging';q.innerHTML=`<h3>🩻 结构化影像报告</h3><div class="img-grid"><div><h4>胸部</h4>${['肺野','心脏轮廓','气管/主支气管','胸膜腔','纵隔','膈肌'].map(x=>`<label class="checkrow"><input type="checkbox" data-img="${x}">${x}</label>`).join('')}</div><div><h4>腹部</h4>${['肝脏','胆囊/胆道','脾脏','胰腺','胃肠道','肾脏','膀胱','腹腔淋巴结','腹腔积液'].map(x=>`<label class="checkrow"><input type="checkbox" data-img="${x}">${x}</label>`).join('')}</div><div><h4>结论</h4><textarea id="imgFind" placeholder="描述异常、测量值、侧别、数量、回声/密度等"></textarea><textarea id="imgImp" placeholder="影像学印象"></textarea><button class="primary" id="imgMake">生成报告</button></div></div><div id="imgOut"></div>`;c.appendChild(q);$('imgMake').onclick=()=>{const checks=[...q.querySelectorAll('[data-img]:checked')].map(x=>x.dataset.img);const text=`结构化影像记录\n检查项目：${checks.join('、')||'未勾选'}\n所见：${$('imgFind').value||'未记录'}\n影像学印象：${$('imgImp').value||'未记录'}\n患者：${ptxt()}\n\n提示：影像学描述与最终诊断应结合原始图像、临床资料及专科复核。`;out('imgOut',`<div class="core-report">${esc(text)}</div><button class="secondary" id="imgCopy">复制</button>`);$('imgCopy').onclick=()=>navigator.clipboard?.writeText(text)} }
  function bind(){inject();labEngine();imaging();document.addEventListener('vct50:patient-change',()=>{renderDashboard();renderCritical()});renderDashboard();renderCritical();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
  window.VCT50_CLINICAL_CORE={renderDashboard,renderCritical,addTrend};
})();
