/* Vet Clinical Toolbox 5.0-r08 · Complete Clinical OS layer
 * Patient-centric, local-first, doctor-confirmed workflow extensions.
 * No AI-generated medication dose is promoted into the formal drug library.
 */
(()=>{
'use strict';
const V='5.0-r08';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const key='vct50_clinical_os_complete';
const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch(_){return {}}};
const store=read();
const now=()=>new Date().toISOString();
const patient=()=>window.VCT50_PATIENT_STATE||window.vetPatientState5||{};
const pid=()=>patient().patientId||patient().id||'UNASSIGNED';
const bucket=()=>store[pid()]||(store[pid()]={labs:[],goals:[],tasks:[],timeline:[],soap:null,candidates:[],evidence:[],pain:[],io:[],audit:[]});
const save=()=>{try{localStorage.setItem(key,JSON.stringify(store))}catch(_){} window.dispatchEvent(new CustomEvent('vct50:os-change',{detail:{patientId:pid()}}));};
function addTimeline(type,title,detail){bucket().timeline.unshift({ts:now(),type,title,detail});bucket().timeline=bucket().timeline.slice(0,100);save();}
function getRef(analyzer){
  try{const a=window.VCT50_LAB_ANALYZERS||window.VCT50_LAB_REFERENCES||{};return a[analyzer]||null}catch(_){return null}
}
function style(){if($('vct50-os-style'))return;const s=document.createElement('style');s.id='vct50-os-style';s.textContent=`
.vct-os-wrap{padding:16px}.os-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.os-tabs{display:flex;gap:6px;overflow:auto;padding:10px 0;position:sticky;top:var(--vct-header-h,64px);z-index:5;background:var(--bg,#fff)}.os-tabs button{white-space:nowrap;border:1px solid var(--line,#dbe4e6);background:#fff;border-radius:9px;padding:7px 10px}.os-tabs button.active{background:#dff7f2;color:#166b61;border-color:#a7ddd5}.os-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.os-stat{border:1px solid var(--line,#dbe4e6);border-radius:12px;padding:12px;background:#fbfdfd;display:flex;flex-direction:column;gap:5px}.os-stat span,.trend-row small{color:#64748b;font-size:12px}.os-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:10px 0}.os-form label{display:flex;flex-direction:column;gap:5px}.os-form input,.os-form select,.os-form textarea{width:100%;box-sizing:border-box}.os-form textarea{min-height:84px}.os-row{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;border-top:1px solid var(--line,#dbe4e6);padding:10px 0}.os-row.done{opacity:.55}.os-row.overdue{border-left:4px solid #b91c1c;padding-left:8px}.trend-row{display:grid;grid-template-columns:90px 110px 100px 1fr;gap:8px;align-items:center;border-top:1px solid var(--line,#dbe4e6);padding:9px 0}.os-pre{white-space:pre-wrap;overflow:auto;background:#f8fafc;border-radius:9px;padding:10px;font-size:12px}.badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#fef3c7}.warning{border:1px solid #f2c3c3;border-radius:10px;padding:10px;background:#fff7f7}.info{border:1px solid #cfe4ef;border-radius:10px;padding:10px;background:#f7fbfd}@media(max-width:760px){.os-head{flex-direction:column}.os-grid,.os-form{grid-template-columns:1fr}.trend-row{grid-template-columns:70px 90px 70px 1fr;font-size:12px}.os-tabs{top:var(--vct-header-h,64px)}}`;document.head.appendChild(s)}
function ensureView(){
 style();
 if($('vct50-os'))return;
 const sec=document.createElement('section');sec.id='vct50-os';sec.className='view';
 sec.innerHTML=`<div class="card vct-os-wrap">
 <div class="os-head"><div><div class="eyebrow">VETERINARY CLINICAL OPERATING SYSTEM · ${V}</div><h2>临床 OS 工作台</h2><p class="muted">Patient State → 问题列表 → 检查趋势 → 治疗目标 → 任务 → 复评 → 病历记录。所有 AI 建议均保持“待核验/医生确认”状态。</p></div><div id="vctOsPatient" class="command-status"></div></div>
 <div class="os-tabs" role="tablist"><button data-tab="overview">总览</button><button data-tab="labs">检验趋势</button><button data-tab="soap">SOAP / POMR</button><button data-tab="goals">目标与复评</button><button data-tab="tasks">住院任务</button><button data-tab="meds">药物安全</button><button data-tab="fluidio">Fluid / I&O</button><button data-tab="pain">疼痛</button><button data-tab="evidence">证据库</button><button data-tab="candidate">AI待核验</button><button data-tab="special">专项工作台</button><button data-tab="timeline">时间线</button></div>
 <div id="vctOsPanels"></div></div>`;
 const clinical=$('clinical'); if(clinical?.parentElement) clinical.parentElement.insertBefore(sec,clinical.nextSibling); else document.querySelector('main')?.appendChild(sec);
 const nav=$('nav'); if(nav&&!nav.querySelector('[data-v="vct50-os"]')){const b=document.createElement('button');b.type='button';b.dataset.v='vct50-os';b.textContent='临床OS';nav.appendChild(b);}
 sec.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.tab)));
}
function render(tab='overview'){
 ensureView();
 document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('vct50-os').classList.add('active');
 document.querySelectorAll('#nav button[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v==='vct50-os'));
 document.querySelectorAll('.os-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 history.replaceState(null,'','#vct50-os'); window.scrollTo({top:0,behavior:'smooth'});
 const p=patient();$('vctOsPatient').innerHTML=p.patientId?`<b>${esc(p.patientId)}</b><br><span>${esc(p.species||'犬')} · ${esc(p.breed||'')} ${p.weight?`· ${esc(p.weight)} kg`:''}</span>`:'未建立患者';
 const panel=$('vctOsPanels'); panel.innerHTML=panelHtml(tab,bucket()); bindPanel(tab); refreshSummary();
}
function panelHtml(tab,b){
 const p=patient();
 if(tab==='overview')return `<div class="os-grid">
 <div class="os-stat"><span>问题</span><b>${esc((p.diagnosis||'未填写').slice(0,50))}</b></div><div class="os-stat"><span>检验快照</span><b>${b.labs.length}</b></div><div class="os-stat"><span>治疗目标</span><b>${b.goals.filter(x=>!x.done).length}</b></div><div class="os-stat"><span>待办任务</span><b>${b.tasks.filter(x=>!x.done).length}</b></div>
 <div class="card"><h3>Red Flags / Safety Gate</h3><div id="vctOsSafety">正在评估…</div></div>
 <div class="card"><h3>Next Best Actions</h3><div id="vctOsNext"></div></div>
 <div class="card"><h3>当前患者事实源</h3><pre class="os-pre">${esc(JSON.stringify({patientId:p.patientId,species:p.species,weight:p.weight,chief:p.chief,history:p.history,diagnosis:p.diagnosis,currentMeds:p.currentMeds,creatinine:p.creatinine,potassium:p.potassium,sodium:p.sodium,albumin:p.albumin,glucose:p.glucose},null,2))}</pre></div>
 <div class="card"><h3>最近事件</h3>${timelineHtml(b.timeline.slice(0,8))}</div></div>`;
 if(tab==='labs')return `<div class="card"><h3>Dynamic Lab Trend · 动态趋势</h3><p class="muted">按患者保存多次快照；趋势只比较真实录入值，不把单次值自动升级为疾病分期。</p><div class="os-form"><label>时间<input id="osLabTs" type="datetime-local"></label><label>项目<select id="osLabName"><option>CRE</option><option>K</option><option>Na</option><option>ALB</option><option>GLU</option><option>BUN</option><option>PHOS</option><option>Ca</option><option>ALT</option><option>AST</option><option>TBIL</option><option>HCT</option><option>HGB</option><option>PLT</option><option>Lactate</option><option>SDMA</option><option>UPC</option><option>SBP</option></select></label><label>数值<input id="osLabVal" type="number" step="any"></label><label>单位<input id="osLabUnit" placeholder="mmol/L, μmol/L…"></label><label>分析仪/参考来源<input id="osLabRef" placeholder="本院纳百 / 实验室报告 / 指南"></label></div><button class="primary" id="osAddLab">保存快照</button><div id="osLabTrend">${labHtml(b.labs)}</div></div>`;
 if(tab==='soap')return `<div class="card"><h3>SOAP / POMR · 病历草稿</h3><p class="muted">自动整理为草稿，医生编辑并确认后再进入正式记录。</p><div class="os-form"><label>S · Subjective<input id="soapS" value="${esc(p.chief||'')}" placeholder="主诉、病史、主人观察"></label><label>O · Objective<textarea id="soapO">${esc(p.notes||'')}</textarea></label><label>A · Assessment<textarea id="soapA">${esc(p.diagnosis||'')}</textarea></label><label>P · Plan<textarea id="soapP">${esc(b.goals.map(g=>g.goal).join('\n'))}</textarea></label></div><div class="toolbar"><button class="primary" id="soapGenerate">从患者状态生成草稿</button><button class="secondary" id="soapSave">保存医生确认前草稿</button></div><div id="soapOut">${b.soap?`<pre class="os-pre">${esc(JSON.stringify(b.soap,null,2))}</pre>`:'尚无草稿'}</div></div>`;
 if(tab==='goals')return `<div class="card"><h3>Treatment Goals + Reassessment · 治疗目标与复评触发器</h3><div class="os-form"><label>目标<input id="goalText" placeholder="例如：呼吸功下降、灌注改善、疼痛下降"></label><label>当前状态<input id="goalCurrent"></label><label>目标状态<input id="goalTarget"></label><label>复评时间<input id="goalDue" type="datetime-local"></label><label>升级/降阶触发条件<textarea id="goalTrigger" placeholder="出现哪些变化需要升级；达到什么条件可以降阶"></textarea></label></div><button class="primary" id="goalAdd">添加目标</button><div>${b.goals.map((g,i)=>`<div class="os-row ${g.done?'done':''}"><div><b>${esc(g.goal)}</b><div class="muted">当前：${esc(g.current)} → 目标：${esc(g.target)} · ${g.due?esc(new Date(g.due).toLocaleString()):'未设复评时间'}</div><small>触发器：${esc(g.trigger||'未设置')}</small></div><button data-goal-done="${i}" class="secondary">${g.done?'恢复':'完成'}</button></div>`).join('')||'<div class="muted">暂无目标</div>'}</div></div>`;
 if(tab==='tasks')return `<div class="card"><h3>Inpatient Task Board · 住院任务板</h3><div class="os-form"><label>任务<input id="taskText" placeholder="体温/血压/尿量/输液检查/复评"></label><label>频率<select id="taskFreq"><option>q1h</option><option>q2h</option><option>q4h</option><option>q6h</option><option>q12h</option><option>q24h</option><option>一次性</option></select></label><label>负责人<select id="taskOwner"><option>医生</option><option>护士</option><option>技术员</option></select></label><label>下次执行<input id="taskDue" type="datetime-local"></label></div><button class="primary" id="taskAdd">添加任务</button><div>${b.tasks.map((t,i)=>{const overdue=!t.done&&t.due&&new Date(t.due)<new Date();return `<div class="os-row ${t.done?'done':''} ${overdue?'overdue':''}"><div><b>${esc(t.text)}</b><div>${esc(t.freq)} · ${esc(t.owner)} · ${t.due?esc(new Date(t.due).toLocaleString()):'未设时间'}</div>${overdue?'<strong>逾期</strong>':''}</div><button data-task-done="${i}" class="secondary">${t.done?'恢复':'完成'}</button></div>`}).join('')||'<div class="muted">暂无任务</div>'}</div></div>`;
 if(tab==='meds')return `<div class="card"><h3>Medication Safety Engine · 药物安全审计</h3><p class="muted">本模块做结构化风险筛查，不替代药品标签、当前指南和执业兽医复核。</p><label>当前用药/计划（每行一项）<textarea id="medAuditText" placeholder="药名 | 剂量 | 途径 | 频率 | 适应证"></textarea></label><button class="primary" id="medAudit">审计</button><div id="medAuditOut"></div></div>`;
 if(tab==='fluidio')return `<div class="card"><h3>Fluid as Drug + I&O · 液体也是药物</h3><div class="os-form"><label>时间<input id="ioTs" type="datetime-local"></label><label>输入 mL<input id="ioIn" type="number" step="any"></label><label>输出 mL<input id="ioOut" type="number" step="any"></label><label>体重 kg<input id="ioWt" type="number" step="any" value="${esc(p.weight||'')}"></label><label>液体/来源<input id="ioSource" placeholder="晶体液/胶体/饮水/尿液/引流"></label></div><button class="primary" id="ioAdd">保存 I&O</button><div id="ioOut">${ioHtml(b.io)}</div><div class="info">每次改变液体处方前重新评估灌注、尿量、体重、呼吸状态、电解质及液体超负荷风险。</div></div>`;
 if(tab==='pain')return `<div class="card"><h3>Pain Workbench · 疼痛趋势</h3><div class="os-form"><label>物种<select id="pwSp"><option>犬</option><option>猫</option></select></label><label>量表/方法<input id="pwScale" placeholder="CMPS-SF / Feline Grimace Scale / 其他"></label><label>评分<input id="pwScore" type="number" step="1" min="0" max="20"></label><label>干预<textarea id="pwIntervention" placeholder="已采取的镇痛措施"></textarea></label></div><button class="primary" id="pwAdd">记录疼痛复评</button><div>${b.pain.map(x=>`<div class="os-row"><div><b>${esc(x.score)}</b> · ${esc(x.scale)}</div><span>${esc(new Date(x.ts).toLocaleString())}</span></div>`).join('')||'<div class="muted">暂无记录</div>'}</div></div>`;
 if(tab==='evidence')return `<div class="card"><h3>Evidence Library · 证据库</h3><div class="os-form"><label>主题<input id="evTopic"></label><label>证据等级<select id="evTier"><option>A · 指南/系统综述</option><option>B · 同行评议/专科共识</option><option>C · 专业参考资料</option><option>D · 本院经验/待核验</option></select></label><label>来源<input id="evSource"></label><label>URL<input id="evUrl"></label><label>最后核验<input id="evVerified" type="date"></label></div><button class="primary" id="evAdd">保存证据条目</button><div>${b.evidence.map((x,i)=>`<div class="os-row"><div><b>${esc(x.topic)}</b><div>${esc(x.tier)} · ${esc(x.source)}</div></div><a target="_blank" rel="noopener" href="${esc(x.url||'#')}">来源</a></div>`).join('')||'<div class="muted">暂无证据条目</div>'}</div></div>`;
 if(tab==='candidate')return `<div class="card"><h3>AI Candidate / 待核验知识</h3><p class="muted">AI 未命中本地正式库时只能进入此层。必须补充来源、核验并由医生确认后，才可用于正式记录；绝不自动写入 427 药物库。</p><div class="os-form"><label>类型<select id="candType"><option>药物</option><option>疾病</option><option>方案</option><option>检查</option></select></label><label>名称<input id="candName"></label><label>AI建议/摘要<textarea id="candText"></textarea></label><label>来源/证据<textarea id="candSource"></textarea></label></div><button class="primary" id="candAdd">保存待核验</button><div>${b.candidates.map((x,i)=>`<div class="os-row"><div><b>${esc(x.name)}</b> · ${esc(x.type)}<div>${esc(x.text)}</div><small>${esc(x.source||'无来源，必须核验')}</small></div><span class="badge">${x.confirmed?'医生已确认':'待核验'}</span></div>`).join('')||'<div class="muted">暂无候选内容</div>'}</div></div>`;
 if(tab==='special')return `<div class="os-grid"><div class="card"><h3>Cardiac Imaging</h3><p>VHS / VLS / VLAS 工作台：录入测量值与品种/投照背景，输出趋势与“需结合临床”提示。</p><div class="os-form"><label>VHS<input id="spVhs" type="number" step="any"></label><label>VLS<input id="spVls" type="number" step="any"></label><label>VLAS<input id="spVlas" type="number" step="any"></label></div><button class="primary" id="spCardiac">评估</button><div id="spCardiacOut"></div></div><div class="card"><h3>Renal / IRIS</h3><p>整合 CRE、SDMA、UPC、BP、尿浓缩能力与趋势；不使用单一数值硬分期。</p><div class="os-form"><label>CRE<input id="spCre" type="number"></label><label>SDMA<input id="spSdma" type="number"></label><label>UPC<input id="spUpc" type="number" step="any"></label><label>SBP<input id="spSbp" type="number"></label><label>USG<input id="spUsg" type="number" step=".001"></label></div><button class="primary" id="spRenal">生成框架</button><div id="spRenalOut"></div></div><div class="card"><h3>ACVIM / MGCS / Dental / Ortho / Exotics</h3><p>提供结构化记录入口：心脏分期、神经评分、Triadan牙位、TPA/TPLO/TTA规划、鸟/兔/啮齿类/爬宠基础安全参数。</p><div class="os-form"><label>专项<select id="spType"><option>ACVIM心脏</option><option>MGCS</option><option>Triadan牙科</option><option>TPA/TPLO/TTA</option><option>Exotics</option><option>TCM</option></select></label><textarea id="spNote" placeholder="记录测量值、临床背景、影像/检查、待核验点"></textarea></div><button class="primary" id="spSave">保存专项记录</button><div id="spOut"></div></div></div>`;
 return timelineHtml(b.timeline);
}
function labHtml(a){if(!a.length)return '<div class="muted">暂无趋势数据。建议先录入至少2个时间点。</div>';const by={};a.forEach(x=>(by[x.name]??=[]).push(x));return Object.entries(by).map(([n,arr])=>{arr.sort((x,y)=>new Date(x.ts)-new Date(y.ts));const last=arr[arr.length-1],prev=arr[arr.length-2];let delta=prev?last.value-prev.value:0;let rate=prev?delta/Math.max(1,(new Date(last.ts)-new Date(prev.ts))/3600000):0;let arrow=delta>0?'↑':delta<0?'↓':'→';return `<div class="trend-row"><b>${esc(n)}</b><span>${esc(last.value)} ${esc(last.unit||'')}</span><strong>${prev?arrow+' '+delta.toFixed(2):'—'}</strong><small>${prev?'变化率 '+rate.toFixed(3)+'/h · '+new Date(last.ts).toLocaleString():'仅1点 · 继续采集趋势'}</small></div>`}).join('')}
function timelineHtml(a){return a.length?a.map(x=>`<div class="os-row"><div><b>${esc(x.title)}</b><div>${esc(x.detail||'')}</div></div><small>${esc(new Date(x.ts).toLocaleString())}</small></div>`).join(''):'<div class="muted">暂无事件</div>'}
function ioHtml(a){return a.slice().reverse().map(x=>`<div class="os-row"><div><b>${esc(x.source||'I&O')}</b><div>输入 ${x.input||0} mL · 输出 ${x.output||0} mL · 净 ${((x.input||0)-(x.output||0)).toFixed(1)} mL${x.weight?` · ${(x.input-x.output)/x.weight>0?((x.input-x.output)/x.weight).toFixed(2):((x.input-x.output)/x.weight).toFixed(2)} mL/kg`:''}</div></div><small>${esc(new Date(x.ts).toLocaleString())}</small></div>`).join('')||'<div class="muted">暂无I&O</div>'}
function bindPanel(tab){const b=bucket();
 if(tab==='labs')$('osAddLab')?.addEventListener('click',()=>{const v=parseFloat($('osLabVal').value);if(!Number.isFinite(v))return alert('请输入有效数值');b.labs.push({ts:$('osLabTs').value?new Date($('osLabTs').value).toISOString():now(),name:$('osLabName').value,value:v,unit:$('osLabUnit').value,ref:$('osLabRef').value});addTimeline('lab','保存检验快照',`${$('osLabName').value}=${v}`);render('labs')});
 if(tab==='soap'){ $('soapGenerate')?.addEventListener('click',()=>{const p=patient();$('soapS').value=p.chief||'';$('soapO').value=[p.notes,p.history].filter(Boolean).join('\n');$('soapA').value=p.diagnosis||'';$('soapP').value=b.goals.filter(x=>!x.done).map(x=>`${x.goal}；复评：${x.due||'未设置'}`).join('\n');}); $('soapSave')?.addEventListener('click',()=>{b.soap={ts:now(),S:$('soapS').value,O:$('soapO').value,A:$('soapA').value,P:$('soapP').value,status:'doctor-review'};addTimeline('record','保存SOAP/POMR草稿','状态：待医生确认');render('soap')});}
 if(tab==='goals'){$('goalAdd')?.addEventListener('click',()=>{if(!$('goalText').value.trim())return;b.goals.push({goal:$('goalText').value,current:$('goalCurrent').value,target:$('goalTarget').value,due:$('goalDue').value?new Date($('goalDue').value).toISOString():'',trigger:$('goalTrigger').value,done:false});addTimeline('goal','新增治疗目标',$('goalText').value);render('goals')});document.querySelectorAll('[data-goal-done]').forEach(x=>x.addEventListener('click',()=>{b.goals[+x.dataset.goalDone].done=!b.goals[+x.dataset.goalDone].done;save();render('goals')}));}
 if(tab==='tasks'){$('taskAdd')?.addEventListener('click',()=>{if(!$('taskText').value.trim())return;b.tasks.push({text:$('taskText').value,freq:$('taskFreq').value,owner:$('taskOwner').value,due:$('taskDue').value?new Date($('taskDue').value).toISOString():'',done:false});addTimeline('task','新增住院任务',$('taskText').value);render('tasks')});document.querySelectorAll('[data-task-done]').forEach(x=>x.addEventListener('click',()=>{b.tasks[+x.dataset.taskDone].done=!b.tasks[+x.dataset.taskDone].done;save();render('tasks')}));}
 if(tab==='meds')$('medAudit')?.addEventListener('click',()=>{$('medAuditOut').innerHTML=medAudit($('medAuditText').value);});
 if(tab==='fluidio')$('ioAdd')?.addEventListener('click',()=>{const input=+($('ioIn').value||0),output=+($('ioOut').value||0),weight=+($('ioWt').value||0);b.io.push({ts:$('ioTs').value?new Date($('ioTs').value).toISOString():now(),input,output,weight,source:$('ioSource').value});addTimeline('fluid','记录I&O',`输入${input}mL / 输出${output}mL`);render('fluidio')});
 if(tab==='pain')$('pwAdd')?.addEventListener('click',()=>{b.pain.push({ts:now(),species:$('pwSp').value,scale:$('pwScale').value,score:$('pwScore').value,intervention:$('pwIntervention').value});addTimeline('pain','疼痛复评',`评分 ${$('pwScore').value}`);render('pain')});
 if(tab==='evidence')$('evAdd')?.addEventListener('click',()=>{b.evidence.push({topic:$('evTopic').value,tier:$('evTier').value,source:$('evSource').value,url:$('evUrl').value,verified:$('evVerified').value});save();render('evidence')});
 if(tab==='candidate')$('candAdd')?.addEventListener('click',()=>{b.candidates.push({ts:now(),type:$('candType').value,name:$('candName').value,text:$('candText').value,source:$('candSource').value,confirmed:false});addTimeline('candidate','保存AI待核验内容',$('candName').value);render('candidate')});
 if(tab==='special'){ $('spCardiac')?.addEventListener('click',()=>{$('spCardiacOut').innerHTML=`<div class="info">已记录测量框架：VHS=${esc($('spVhs').value||'—')}；VLS=${esc($('spVls').value||'—')}；VLAS=${esc($('spVlas').value||'—')}。需结合物种、品种、投照质量与临床背景，不能仅凭单值下诊断。</div>`}); $('spRenal')?.addEventListener('click',()=>{$('spRenalOut').innerHTML=`<div class="warning">IRIS框架：CRE=${esc($('spCre').value||'—')}，SDMA=${esc($('spSdma').value||'—')}，UPC=${esc($('spUpc').value||'—')}，SBP=${esc($('spSbp').value||'—')}，USG=${esc($('spUsg').value||'—')}。请结合稳定状态、趋势、尿浓缩能力、蛋白尿与血压，并按当前IRIS标准核验。</div>`}); $('spSave')?.addEventListener('click',()=>{addTimeline('special',$('spType').value,$('spNote').value||'专项记录');$('spOut').innerHTML='<div class="info">已保存到患者时间线。</div>'});}
}
function medAudit(text){const lines=String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);const p=patient();const warnings=[];if(/(美洛昔康|meloxicam|卡洛芬|carprofen|酮洛芬|ketoprofen|罗本考昔|robenacoxib|NSAID)/i.test(text)&&/(地塞米松|泼尼松|predni|methylpred|dexameth)/i.test(text))warnings.push('NSAID + corticosteroid：潜在胃肠道/肾脏风险，应确认适应证、时间间隔及替代方案。');if(p.creatinine&&+p.creatinine>236&&/(庆大霉素|gentamicin|阿米卡星|amikacin|妥布霉素|tobramycin)/i.test(text))warnings.push('肾功能异常背景下出现 aminoglycoside：需核对肾毒性风险、适应证、监测和剂量调整。');if(/抗生素|amoxic|amoxi|cefa|cef|enrof|marbo|metronidazole|甲硝唑/i.test(text))warnings.push('Antimicrobial stewardship：确认感染证据、采样/培养适应性、疗程、复评与降阶条件。');if(potassiumRisk(p))warnings.push('当前患者存在电解质高风险信号；高风险处方需结合最新K、ECG、尿量及复查。');return `<div class="${warnings.length?'warning':'info'}"><b>${warnings.length?'发现 '+warnings.length+' 项需要复核':'未发现规则级明显冲突'}</b><ul>${warnings.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>仍需核对具体制剂标签、剂量、途径、频率、禁忌和患者实时状态。</li>'}</ul></div><div class="muted">审计对象：${esc(lines.join('；'))}</div>`}
function potassiumRisk(p){const k=+p.potassium;return Number.isFinite(k)&&k>=5.5}
function safetyHtml(){const p=patient(),r=[];if(potassiumRisk(p))r.push('K ≥5.5 mmol/L：高钾风险，优先确认ECG、重复电解质、尿量/尿路与酸碱状态。');if(+p.creatinine>4&&potassiumRisk(p))r.push('CRE 与 K 同时异常：考虑少尿/无尿、尿路梗阻或严重肾功能异常，需立即临床复核。');if(/呼吸困难|喘|呼吸急促/i.test(String(p.chief||'')))r.push('呼吸困难：Airway/Breathing/Circulation 优先，氧合与POCUS/影像应并行评估。');if(!p.patientId)r.push('尚未建立患者身份：不要把AI建议写入正式病历。');return r.length?`<div class="warning"><ul>${r.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'<div class="info">当前结构化字段未触发高优先级规则；仍需结合完整病史与实时监测。</div>'}
function refreshSummary(){if($('vctOsSafety'))$('vctOsSafety').innerHTML=safetyHtml();if($('vctOsNext')){$('vctOsNext').innerHTML='<ul><li>先确认 Patient State 身份与体重</li><li>优先处理 Red Flags，再完善 Problem List</li><li>对异常指标建立至少2个时间点趋势</li><li>为每个治疗目标设置复评时间与升级/降阶触发器</li><li>高风险药物/液体/麻醉/CPR结果必须医生确认</li></ul>'}}
function boot(){ensureView();const n=$('nav');if(n&&!n.querySelector('[data-v="vct50-os"]')){const b=document.createElement('button');b.type='button';b.dataset.v='vct50-os';b.textContent='临床OS';n.appendChild(b)};n?.querySelector('[data-v="vct50-os"]')?.addEventListener('click',()=>render('overview'));window.addEventListener('vct50:patient-change',()=>{if($('vct50-os')?.classList.contains('active'))render('overview')});window.addEventListener('vct50:os-change',()=>{if($('vct50-os')?.classList.contains('active'))render('overview')});if(location.hash==='#vct50-os')render('overview');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.VCT50ClinicalOSComplete={render,addTimeline,getPatientBucket:bucket,version:V};
})();
