/* VCT Hospital OS 5.0-r08 — phases 1-6
 * Local-first hospital infrastructure layered over Patient State/Clinical OS.
 * No destructive migration. Enterprise records use localStorage for portability;
 * schema is versioned and storage/UI are intentionally decoupled for future IndexedDB/backend sync.
 */
(function(){
'use strict';
const KEY='vct50_hospital_os_v1';
const MODE=(window.VCT50_PRODUCT_MODE||'hospital');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=p=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
const now=()=>new Date().toISOString();
const blank=()=>({version:1,updatedAt:now(),clients:[],pets:[],visits:[],appointments:[],tasks:[],invoices:[],inventory:[],procedures:[],hospitalizations:[],followups:[],timeline:[],staff:[],messages:[],memberships:[],audit:[]});
function load(){try{return Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{return blank();}}
let DB=load();
function save(){DB.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(DB));}
function audit(action,entity,id,meta={}){DB.audit.unshift({id:uid('aud'),at:now(),actor:'当前用户',action,entity,entityId:id,meta});DB.audit=DB.audit.slice(0,1000);}
function timeline(type,entity,id,text,meta={}){DB.timeline.unshift({id:uid('tl'),at:now(),type,entity,entityId:id,text,meta});DB.timeline=DB.timeline.slice(0,2000);}
function el(id){return document.getElementById(id)}
function toast(msg){let x=el('vctHosToast');if(!x){x=document.createElement('div');x.id='vctHosToast';x.style='position:fixed;right:14px;bottom:14px;z-index:100;background:#123;color:#fff;padding:10px 14px;border-radius:10px;box-shadow:0 8px 30px #0003';document.body.appendChild(x)}x.textContent=msg;setTimeout(()=>x.remove(),2200)}
function upsert(arr,item){const i=arr.findIndex(x=>x.id===item.id);if(i>=0)arr[i]=item;else arr.unshift(item);}
function nav(){
 const n=document.querySelector('#nav'); if(!n)return;
 const items=[['hos','🏥医院驾驶舱'],['crm','👥客户/宠物'],['visit','🩺就诊/EMR'],['queue','📋预约/排队'],['business','💳收费/会员'],['inventory','💊药房/库存'],['inpatient','🛏住院/ICU'],['surgery','🔪手术/麻醉'],['owner','🐾宠主端'],['aihos','🤖AI医院大脑'],['audit','🧾审计/数据']];
 if(MODE==='lite') items.splice(4,4);
 items.forEach(([id,label])=>{if(!n.querySelector('[data-v="'+id+'"]')){const b=document.createElement('button');b.dataset.v=id;b.textContent=label;n.appendChild(b);b.onclick=()=>show(id)}});
}
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));const x=el(id);if(x)x.classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===id));location.hash=id;render(id)}
function css(){if(el('vctHosCss'))return;const s=document.createElement('style');s.id='vctHosCss';s.textContent=`
.vct-hos-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.vct-hos-stat{padding:14px;border:1px solid var(--line,#dce7e3);border-radius:12px;background:#fff}.vct-hos-stat b{font-size:24px;display:block}.vct-hos-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.vct-hos-toolbar input,.vct-hos-toolbar select{min-width:150px}.vct-hos-table{width:100%;border-collapse:collapse;font-size:13px}.vct-hos-table th,.vct-hos-table td{border-bottom:1px solid var(--line,#e5e7eb);padding:8px;text-align:left;vertical-align:top}.vct-hos-card{border:1px solid var(--line,#dce7e3);border-radius:12px;padding:12px;margin:10px 0;background:#fff}.vct-hos-kpi{font-size:12px;color:#64748b}.vct-hos-danger{background:#fff7ed;border-left:4px solid #ea580c;padding:8px}.vct-hos-ok{background:#f0fdf4;border-left:4px solid #16a34a;padding:8px}.vct-hos-muted{color:#64748b}.vct-hos-pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef6f4;font-size:11px;margin:2px}.vct-hos-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.vct-hos-form label{font-size:12px}.vct-hos-form input,.vct-hos-form select,.vct-hos-form textarea{width:100%;box-sizing:border-box}.vct-hos-form textarea{min-height:70px}.vct-hos-actions button{margin:3px}.vct-hos-ai{background:linear-gradient(135deg,#f6fffd,#f5f8ff);border:1px solid #cfe8e2}.vct-hos-timeline{max-height:360px;overflow:auto}.vct-hos-tl{padding:8px;border-bottom:1px solid #e5e7eb}.vct-hos-section{margin-top:14px}.vct-hos-sign{font-size:11px;color:#475569}@media(max-width:900px){.vct-hos-grid{grid-template-columns:repeat(2,1fr)}.vct-hos-form{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function shell(){
 const anchor=document.querySelector('body>script:last-of-type');
 const wrap=document.createElement('div');wrap.id='vctHospitalShell';
 wrap.innerHTML=`
 <section id="hos" class="view"><div class="card"><h2>🏥 VCT Hospital OS 5.0-r08</h2><div class="vct-hos-kpi">1–6阶段：医院基础设施 → 医疗闭环 → 经营 → 住院/手术 → 宠主端 → AI医院大脑</div><div id="hosKpi" class="vct-hos-grid vct-hos-section"></div><div class="vct-hos-card"><h3>今日工作流</h3><div id="hosToday"></div></div></div></section>
 <section id="crm" class="view"><div class="card"><h2>👥 客户 / 宠物 CRM</h2><div class="vct-hos-toolbar"><input id="crmQ" placeholder="搜索主人/手机号/宠物/病历号"><button class="primary" id="crmSearch">搜索</button><button class="secondary" id="crmNew">新建客户+宠物</button></div><div id="crmForm"></div><div id="crmList"></div></div></section>
 <section id="visit" class="view"><div class="card"><h2>🩺 就诊 / EMR / POMR</h2><div class="vct-hos-toolbar"><select id="visitPet"></select><button class="primary" id="visitNew">新建就诊</button><button class="secondary" id="visitLoadCurrent">载入当前 Patient State</button></div><div id="visitForm"></div><div id="visitList"></div></div></section>
 <section id="queue" class="view"><div class="card"><h2>📋 预约 / 排队 / 前台工作台</h2><div class="vct-hos-toolbar"><button class="primary" id="apptNew">新建预约</button><select id="queueStatus"><option value="">全部状态</option><option>待到院</option><option>已到院</option><option>就诊中</option><option>已完成</option><option>取消</option></select></div><div id="apptForm"></div><div id="queueList"></div></div></section>
 <section id="business" class="view"><div class="card"><h2>💳 收费 / 会员 / 经营</h2><div class="vct-hos-grid" id="bizKpi"></div><div class="vct-hos-toolbar"><button class="primary" id="invoiceNew">新建收费</button><button class="secondary" id="memberNew">新建会员</button></div><div id="bizForm"></div><div id="bizList"></div></div></section>
 <section id="inventory" class="view"><div class="card"><h2>💊 药房 / 库存 / 采购</h2><div class="vct-hos-grid" id="invKpi"></div><div class="vct-hos-toolbar"><button class="primary" id="invNew">入库/调整库存</button><button class="secondary" id="invLow">只看低库存</button></div><div id="invForm"></div><div id="invList"></div></div></section>
 <section id="inpatient" class="view"><div class="card"><h2>🛏 住院 / ICU / 护理</h2><div class="vct-hos-toolbar"><button class="primary" id="admNew">新建住院</button></div><div id="admForm"></div><div id="admList"></div></div></section>
 <section id="surgery" class="view"><div class="card"><h2>🔪 手术 / 麻醉 / 围术期</h2><div class="vct-hos-toolbar"><button class="primary" id="surgNew">新建手术</button></div><div id="surgForm"></div><div id="surgList"></div></div></section>
 <section id="owner" class="view"><div class="card"><h2>🐾 VCT Pet · 宠主端</h2><div class="vct-hos-card"><b>宠主可见信息边界</b><p class="vct-hos-muted">预约、就诊状态、医嘱、报告摘要、处方、复诊提醒；未经授权不展示内部审计、成本、员工绩效及未审核 AI 建议。</p></div><div id="ownerPortal"></div></div></section>
 <section id="aihos" class="view"><div class="card"><h2>🤖 AI Hospital Brain</h2><div class="vct-hos-grid"><div class="vct-hos-card vct-hos-ai"><b>AI Doctor</b><p>病例摘要、问题列表、红旗、鉴别诊断、检查建议、治疗思路。</p></div><div class="vct-hos-card vct-hos-ai"><b>AI Nurse</b><p>任务优先级、监测提醒、复评、住院护理清单。</p></div><div class="vct-hos-card vct-hos-ai"><b>AI Manager</b><p>收入、客流、复诊率、库存、人员工作量。</p></div><div class="vct-hos-card vct-hos-ai"><b>AI Marketing</b><p>客户分层、复诊提醒、内容主题、活动候选。</p></div></div><div class="vct-hos-card"><h3>AI 工作台</h3><div class="vct-hos-toolbar"><button class="primary" id="aiHosAnalyze">生成医院级分析</button><button class="secondary" id="aiHosExport">导出 AI 上下文 JSON</button></div><div id="aiHosOut"></div></div></div></section>
 <section id="audit" class="view"><div class="card"><h2>🧾 审计 / 数据 / 备份</h2><div class="vct-hos-toolbar"><button class="primary" id="dataExport">导出医院数据 JSON</button><button class="secondary" id="dataImportBtn">导入 JSON</button><input id="dataImport" type="file" accept="application/json" style="display:none"><button class="secondary" id="dataClear">清空本机医院 OS 数据</button></div><div id="auditList"></div></div></section>`;
 document.body.insertBefore(wrap,anchor||null);
}
function renderHos(){
 const k=el('hosKpi');if(!k)return;const today=new Date().toISOString().slice(0,10);const ap=DB.appointments.filter(x=>x.time?.slice(0,10)===today);const vis=DB.visits.filter(x=>x.createdAt?.slice(0,10)===today);const open=DB.hospitalizations.filter(x=>x.status==='住院中');const low=DB.inventory.filter(x=>(x.qty??0)<=(x.minQty??0));
 k.innerHTML=[['今日预约',ap.length,'appointments'],['今日就诊',vis.length,'visits'],['住院中',open.length,'inpatients'],['低库存',low.length,'inventory']].map(x=>`<div class="vct-hos-stat"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');
 el('hosToday').innerHTML=`<div class="vct-hos-ok">建议顺序：前台队列 → ABCDE/红旗分流 → POMR/Problem List → 检查/处方 → 医嘱与复诊 → 收费/库存 → 审计。</div><div class="vct-hos-section vct-hos-timeline">${DB.timeline.slice(0,12).map(x=>`<div class="vct-hos-tl"><b>${esc(x.type)}</b> · ${new Date(x.at).toLocaleString()}<br>${esc(x.text)}</div>`).join('')||'<span class="vct-hos-muted">暂无事件</span>'}</div>`;
}
function crmForm(){el('crmForm').innerHTML=`<div class="vct-hos-card"><div class="vct-hos-form"><label>主人姓名<input id="fOwner"></label><label>手机号<input id="fPhone"></label><label>宠物姓名<input id="fPet"></label><label>物种<select id="fSpecies"><option>犬</option><option>猫</option><option>鸟类</option><option>兔/啮齿类</option><option>爬宠</option><option>其他</option></select></label><label>品种<input id="fBreed"></label><label>病历号<input id="fCase"></label></div><div class="vct-hos-actions"><button class="primary" id="crmSave">保存</button></div></div>`;el('crmSave').onclick=()=>{const c={id:uid('cli'),name:el('fOwner').value.trim(),phone:el('fPhone').value.trim(),createdAt:now()};const p={id:uid('pet'),clientId:c.id,name:el('fPet').value.trim(),species:el('fSpecies').value,breed:el('fBreed').value.trim(),caseId:el('fCase').value.trim(),createdAt:now()};if(!c.name&&!c.phone){toast('至少填写主人姓名或手机号');return}DB.clients.unshift(c);DB.pets.unshift(p);audit('create','client',c.id,{petId:p.id});timeline('CRM','client',c.id,`新建客户 ${c.name} / 宠物 ${p.name}`);save();toast('客户与宠物已保存');render('crm')};}
function renderCrm(){const q=(el('crmQ')?.value||'').trim().toLowerCase();const arr=DB.pets.filter(p=>{const c=DB.clients.find(x=>x.id===p.clientId)||{};return !q||JSON.stringify({...p,...c}).toLowerCase().includes(q)});el('crmList').innerHTML=arr.map(p=>{const c=DB.clients.find(x=>x.id===p.clientId)||{};const v=DB.visits.filter(x=>x.petId===p.id).length;return `<div class="vct-hos-card"><b>${esc(p.name||'未命名')}</b> <span class="vct-hos-pill">${esc(p.species)}</span><div>主人：${esc(c.name)} · ${esc(c.phone)} · 病历号：${esc(p.caseId)}</div><div class="vct-hos-kpi">就诊 ${v} 次 · 创建 ${new Date(p.createdAt).toLocaleDateString()}</div><div class="vct-hos-actions"><button data-act="visit" data-id="${p.id}">新建就诊</button><button data-act="follow" data-id="${p.id}">复诊</button></div></div>`}).join('')||'<div class="vct-hos-muted">暂无匹配。</div>';el('crmList').querySelectorAll('button').forEach(b=>b.onclick=()=>{const p=DB.pets.find(x=>x.id===b.dataset.id);if(b.dataset.act==='visit'||b.dataset.act==='follow'){show('visit');el('visitPet').value=p.id;renderVisitForm(p,b.dataset.act==='follow')}});}
function petOptions(id){const opts=DB.pets.map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${esc(p.name||'未命名')} · ${esc(p.species)} · ${esc((DB.clients.find(c=>c.id===p.clientId)||{}).name||'')}</option>`).join('');return opts||'<option value="">暂无宠物</option>'}
function renderVisit(){el('visitPet').innerHTML=petOptions(DB.visits[0]?.petId);renderVisitForm();}
function renderVisitForm(p,follow=false){p=p||DB.pets.find(x=>x.id===el('visitPet')?.value);if(!p){el('visitForm').innerHTML='<div class="vct-hos-muted">请先建立宠物档案。</div>';return}el('visitForm').innerHTML=`<div class="vct-hos-card"><div class="vct-hos-form"><label>就诊类型<select id="vfType"><option>${follow?'复诊':'初诊'}</option><option>急诊</option><option>住院复评</option><option>术后复查</option></select></label><label>主诉<textarea id="vfChief"></textarea></label><label>现病史<textarea id="vfHistory"></textarea></label><label>Problem List<textarea id="vfProblems" placeholder="问题1；问题2"></textarea></label><label>检查/检验<textarea id="vfTests"></textarea></label><label>结果/异常<textarea id="vfResults"></textarea></label><label>评估 Assessment<textarea id="vfAssessment"></textarea></label><label>计划 Plan<textarea id="vfPlan"></textarea></label><label>医嘱/监测<textarea id="vfAdvice"></textarea></label><label>复诊日期<input id="vfFollow" type="date"></label></div><div class="vct-hos-actions"><button class="primary" id="vfSave">保存就诊</button><button id="vfAi">同步到 AI Clinical Copilot</button></div></div>`;el('vfSave').onclick=()=>{const v={id:uid('vis'),petId:p.id,createdAt:now(),type:el('vfType').value,chief:el('vfChief').value,history:el('vfHistory').value,problems:el('vfProblems').value,tests:el('vfTests').value,results:el('vfResults').value,assessment:el('vfAssessment').value,plan:el('vfPlan').value,advice:el('vfAdvice').value,followup:el('vfFollow').value,status:'open'};DB.visits.unshift(v);DB.followups.unshift({id:uid('fu'),petId:p.id,visitId:v.id,due:v.followup,status:v.followup?'待跟进':'无需设置'});audit('create','visit',v.id);timeline('Visit','visit',v.id,`${v.type}：${p.name}`);save();toast('就诊已保存');render('visit')};el('vfAi').onclick=()=>{if(window.VCT50_PATIENT_STATE){const c=DB.clients.find(x=>x.id===p.clientId)||{};const map={patientId:p.caseId||p.id,species:p.species,breed:p.breed,petName:p.name,ownerName:c.name,ownerPhone:c.phone,chief:el('vfChief').value,history:el('vfHistory').value,diagnosis:el('vfAssessment').value,currentMeds:''};Object.entries(map).forEach(([k,val])=>{const i=document.getElementById(k==='patientId'?'patientId':k);if(i)i.value=val||''});window.dispatchEvent(new CustomEvent('vct50:patient-change'));}toast('已尝试同步当前患者状态，请在 AI Clinical Copilot 中复核')};}
function renderVisitList(){el('visitList').innerHTML=DB.visits.slice(0,30).map(v=>{const p=DB.pets.find(x=>x.id===v.petId)||{};return `<div class="vct-hos-card"><b>${esc(p.name)}</b> · ${esc(v.type)} · ${new Date(v.createdAt).toLocaleString()}<div><b>主诉：</b>${esc(v.chief)}</div><div><b>Assessment：</b>${esc(v.assessment)}</div><div><b>Plan：</b>${esc(v.plan)}</div><div class="vct-hos-sign">状态：${esc(v.status)} · 记录属于医疗档案；修改应留下审计轨迹。</div></div>`}).join('')||'<div class="vct-hos-muted">暂无就诊。</div>'}
function renderQueue(){const s=el('queueStatus')?.value||'';const arr=DB.appointments.filter(x=>!s||x.status===s);el('queueList').innerHTML=arr.map(a=>{const p=DB.pets.find(x=>x.id===a.petId)||{};return `<div class="vct-hos-card"><b>${new Date(a.time).toLocaleString()}</b> · ${esc(p.name)} · ${esc(a.type)} <span class="vct-hos-pill">${esc(a.status)}</span><div>${esc(a.note||'')}</div><div class="vct-hos-actions">${['已到院','就诊中','已完成','取消'].map(x=>`<button data-q="${x}" data-id="${a.id}">${x}</button>`).join('')}</div></div>`}).join('')||'<div class="vct-hos-muted">暂无预约。</div>';el('queueList').querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=DB.appointments.find(x=>x.id===b.dataset.id);a.status=b.dataset.q;a.updatedAt=now();audit('update','appointment',a.id,{status:a.status});timeline('Queue','appointment',a.id,`队列状态：${a.status}`);save();render('queue')})}
function apptForm(){el('apptForm').innerHTML=`<div class="vct-hos-card"><div class="vct-hos-form"><label>宠物<select id="afPet">${petOptions()}</select></label><label>时间<input id="afTime" type="datetime-local"></label><label>类型<select id="afType"><option>普通门诊</option><option>急诊</option><option>复诊</option><option>疫苗</option><option>手术</option><option>住院复评</option></select></label><label>备注<textarea id="afNote"></textarea></label></div><button class="primary" id="afSave">保存预约</button></div>`;el('afSave').onclick=()=>{const a={id:uid('apt'),petId:el('afPet').value,time:new Date(el('afTime').value||Date.now()).toISOString(),type:el('afType').value,note:el('afNote').value,status:'待到院',createdAt:now()};DB.appointments.unshift(a);audit('create','appointment',a.id);timeline('Appointment','appointment',a.id,'创建预约');save();toast('预约已创建');render('queue')};}
function renderBiz(){const rev=DB.invoices.reduce((s,x)=>s+(Number(x.amount)||0),0);const unpaid=DB.invoices.filter(x=>x.status!=='已支付').length;el('bizKpi').innerHTML=[['累计账单',DB.invoices.length],['应收/记录',rev.toFixed(2)],['未支付',unpaid],['会员',DB.memberships.length]].map(x=>`<div class="vct-hos-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');el('bizList').innerHTML=DB.invoices.slice(0,30).map(i=>`<div class="vct-hos-card"><b>${esc(i.item)}</b> · ¥${Number(i.amount||0).toFixed(2)} · <span class="vct-hos-pill">${esc(i.status)}</span><div>${new Date(i.createdAt).toLocaleString()}</div></div>`).join('')||'<div class="vct-hos-muted">暂无收费记录。</div>';}
function bizForm(kind){el('bizForm').innerHTML=`<div class="vct-hos-card"><div class="vct-hos-form">${kind==='invoice'?'<label>项目<input id="bfItem" value="门诊服务"></label><label>金额<input id="bfAmount" type="number" step="0.01"></label><label>支付状态<select id="bfStatus"><option>待支付</option><option>已支付</option></select></label>':'<label>会员名称<input id="mfName"></label><label>手机号<input id="mfPhone"></label><label>会员等级<input id="mfLevel" value="普通"></label>'}</div><button class="primary" id="bfSave">保存</button></div>`;el('bfSave').onclick=()=>{if(kind==='invoice'){const i={id:uid('inv'),item:el('bfItem').value,amount:Number(el('bfAmount').value||0),status:el('bfStatus').value,createdAt:now()};DB.invoices.unshift(i);audit('create','invoice',i.id);timeline('Billing','invoice',i.id,`收费 ${i.item} ¥${i.amount}`)}else{const m={id:uid('mem'),name:el('mfName').value,phone:el('mfPhone').value,level:el('mfLevel').value,createdAt:now()};DB.memberships.unshift(m);audit('create','membership',m.id);timeline('CRM','membership',m.id,`会员 ${m.name}`)}save();toast('已保存');render('business')};}
function renderInv(lowOnly=false){const arr=DB.inventory.filter(x=>!lowOnly||((x.qty??0)<=(x.minQty??0)));el('invKpi').innerHTML=[['SKU',DB.inventory.length],['低库存',DB.inventory.filter(x=>(x.qty??0)<=(x.minQty??0)).length],['总数量',DB.inventory.reduce((s,x)=>s+(Number(x.qty)||0),0)],['AI候选药物',0]].map(x=>`<div class="vct-hos-stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');el('invList').innerHTML=arr.map(i=>`<div class="vct-hos-card"><b>${esc(i.name)}</b> · 数量 ${i.qty} · 最低 ${i.minQty} · ${esc(i.unit||'单位')} ${i.qty<=i.minQty?'<span class="vct-hos-pill">低库存</span>':''}<div>批号：${esc(i.batch)} · 有效期：${esc(i.expiry)}</div></div>`).join('')||'<div class="vct-hos-muted">暂无库存。</div>'}
function invForm(){el('invForm').innerHTML=`<div class="vct-hos-card"><div class="vct-hos-form"><label>药品/耗材<input id="ifName"></label><label>数量变动<input id="ifQty" type="number"></label><label>最低库存<input id="ifMin" type="number" value="5"></label><label>单位<input id="ifUnit" value="盒"></label><label>批号<input id="ifBatch"></label><label>有效期<input id="ifExpiry" type="date"></label></div><button class="primary" id="ifSave">保存库存变动</button></div>`;el('ifSave').onclick=()=>{const name=el('ifName').value.trim();let i=DB.inventory.find(x=>x.name===name);if(!i){i={id:uid('sku'),name,qty:0,minQty:Number(el('ifMin').value||0),unit:el('ifUnit').value,batch:el('ifBatch').value,expiry:el('ifExpiry').value};DB.inventory.unshift(i)}i.qty+=Number(el('ifQty').value||0);i.minQty=Number(el('ifMin').value||i.minQty);audit('stock','inventory',i.id,{delta:Number(el('ifQty').value||0)});timeline('Inventory','inventory',i.id,`${i.name} 库存变动`);save();toast('库存已更新');render('inventory')};}
function renderAdm(){el('admList').innerHTML=DB.hospitalizations.map(a=>{const p=DB.pets.find(x=>x.id===a.petId)||{};return `<div class="vct-hos-card"><b>${esc(p.name)}</b> · ${esc(a.ward)} · <span class="vct-hos-pill">${esc(a.status)}</span><div>入院：${new Date(a.admit).toLocaleString()} · 主诊：${esc(a.doctor)}</div><div>护理重点：${esc(a.nursing)}</div><div class="vct-hos-actions"><button data-id="${a.id}" data-st="出院">出院</button><button data-id="${a.id}" data-st="ICU观察">转ICU观察</button></div></div>`}).join('')||'<div class="vct-hos-muted">暂无住院病例。</div>';el('admList').querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=DB.hospitalizations.find(x=>x.id===b.dataset.id);a.status=b.dataset.st;a.discharge=a.status==='出院'?now():a.discharge;audit('update','hospitalization',a.id,{status:a.status});timeline('Inpatient','hospitalization',a.id,`住院状态：${a.status}`);save();render('inpatient')})}
function admForm(){el('admForm').innerHTML=`<div class="vct-hos-card"><div class="vct-hos-form"><label>宠物<select id="adPet">${petOptions()}</select></label><label>病区<input id="adWard" value="普通住院区"></label><label>主诊医生<input id="adDoc"></label><label>护理重点<textarea id="adNurse"></textarea></label></div><button class="primary" id="adSave">收治入院</button></div>`;el('adSave').onclick=()=>{const a={id:uid('adm'),petId:el('adPet').value,ward:el('adWard').value,doctor:el('adDoc').value,nursing:el('adNurse').value,admit:now(),status:'住院中'};DB.hospitalizations.unshift(a);audit('admit','hospitalization',a.id);timeline('Inpatient','hospitalization',a.id,'收治入院');save();toast('已收治');render('inpatient')};}
function renderSurg(){el('surgList').innerHTML=DB.procedures.map(s=>{const p=DB.pets.find(x=>x.id===s.petId)||{};return `<div class="vct-hos-card"><b>${esc(p.name)}</b> · ${esc(s.procedure)} · <span class="vct-hos-pill">${esc(s.status)}</span><div>麻醉：${esc(s.anesthesia)} · 医生：${esc(s.doctor)}</div><div>术前风险：${esc(s.risk)}</div></div>`}).join('')||'<div class="vct-hos-muted">暂无手术。</div>'}
function surgForm(){el('surgForm').innerHTML=`<div class="vct-hos-card"><div class="vct-hos-form"><label>宠物<select id="sfPet">${petOptions()}</select></label><label>手术名称<input id="sfProc"></label><label>麻醉方案<textarea id="sfAnes"></textarea></label><label>主刀/麻醉医生<input id="sfDoc"></label><label>术前风险<textarea id="sfRisk"></textarea></label><label>围术期计划<textarea id="sfPlan"></textarea></label></div><button class="primary" id="sfSave">建立手术记录</button></div>`;el('sfSave').onclick=()=>{const s={id:uid('surg'),petId:el('sfPet').value,procedure:el('sfProc').value,anesthesia:el('sfAnes').value,doctor:el('sfDoc').value,risk:el('sfRisk').value,plan:el('sfPlan').value,status:'术前评估',createdAt:now()};DB.procedures.unshift(s);audit('create','procedure',s.id);timeline('Surgery','procedure',s.id,`建立手术：${s.procedure}`);save();toast('手术记录已建立');render('surgery')};}
function owner(){const p=DB.pets[0];if(!p){el('ownerPortal').innerHTML='<div class="vct-hos-muted">暂无宠物档案。</div>';return}const v=DB.visits.filter(x=>x.petId===p.id)[0];el('ownerPortal').innerHTML=`<div class="vct-hos-card"><h3>${esc(p.name)} · ${esc(p.species)}</h3><p>就诊状态：${esc(v?.status||'暂无就诊')}</p><p>最近医嘱：${esc(v?.advice||'暂无')}</p><p>复诊：${esc(v?.followup||'未设置')}</p><div class="vct-hos-ok">宠主端只展示经医院授权的内容。AI建议必须经医生审核后才能成为可见医嘱。</div></div>`}
function ai(){const ctx={mode:MODE,patients:DB.pets.length,clients:DB.clients.length,todayAppointments:DB.appointments.filter(x=>x.time?.slice(0,10)===new Date().toISOString().slice(0,10)).length,visits:DB.visits.length,inpatients:DB.hospitalizations.filter(x=>x.status==='住院中').length,lowStock:DB.inventory.filter(x=>(x.qty??0)<=(x.minQty??0)).map(x=>x.name),unpaid:DB.invoices.filter(x=>x.status!=='已支付').length,followupsDue:DB.followups.filter(x=>x.status==='待跟进').length};el('aiHosOut').innerHTML=`<div class="result"><h4>医院级摘要</h4><pre style="white-space:pre-wrap;font:inherit">${esc(JSON.stringify(ctx,null,2))}</pre><div class="vct-hos-danger">AI只提供分析候选，不自动执行收费、处方、库存调整、消息发送或医疗决策。涉及剂量/处方必须回到正式药库、当前制剂标签/指南与执业兽医审核。</div></div>`}
function auditView(){el('auditList').innerHTML=`<div class="vct-hos-card"><b>数据结构版本：</b>v1 · <b>记录：</b>${DB.audit.length} 条审计 / ${DB.timeline.length} 条时间线<div class="vct-hos-timeline">${DB.audit.slice(0,80).map(a=>`<div class="vct-hos-tl">${new Date(a.at).toLocaleString()} · ${esc(a.action)} · ${esc(a.entity)} · ${esc(a.entityId)}</div>`).join('')}</div></div>`}
function render(id){if(id==='hos')renderHos();if(id==='crm'){crmForm();renderCrm()}if(id==='visit'){renderVisit();renderVisitList()}if(id==='queue')renderQueue();if(id==='business')renderBiz();if(id==='inventory')renderInv();if(id==='inpatient')renderAdm();if(id==='surgery')renderSurg();if(id==='owner')owner();if(id==='aihos'){}if(id==='audit')auditView()}
function bind(){
 el('crmSearch').onclick=renderCrm;el('crmQ').oninput=()=>renderCrm();el('crmNew').onclick=crmForm;el('visitNew').onclick=()=>renderVisitForm();el('visitLoadCurrent').onclick=()=>{const p=window.VCT50_PATIENT_STATE?.getState?.();if(!p)return toast('当前 Patient State 不可用');const pet=DB.pets.find(x=>x.name===p.petName)||DB.pets.find(x=>x.caseId===p.patientId);if(pet){el('visitPet').value=pet.id;renderVisitForm(pet)}else toast('当前患者尚未建立医院档案')};el('queueStatus').onchange=renderQueue;el('apptNew').onclick=apptForm;el('invoiceNew').onclick=()=>bizForm('invoice');el('memberNew').onclick=()=>bizForm('member');el('invNew').onclick=invForm;el('invLow').onclick=()=>renderInv(true);el('admNew').onclick=admForm;el('surgNew').onclick=surgForm;el('aiHosAnalyze').onclick=ai;el('aiHosExport').onclick=()=>download('vct50-ai-hospital-context.json',JSON.stringify({DB,patientState:window.VCT50_PATIENT_STATE?.getState?.()||null},null,2));el('dataExport').onclick=()=>download('vct50-hospital-os-backup.json',JSON.stringify(DB,null,2));el('dataImportBtn').onclick=()=>el('dataImport').click();el('dataImport').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{DB=Object.assign(blank(),JSON.parse(r.result));save();toast('导入成功');render(location.hash.slice(1)||'hos')}catch{toast('JSON格式无效')}};r.readAsText(f)};el('dataClear').onclick=()=>{if(confirm('确认清空本机医院 OS 数据？不会删除正式药物数据库。')){DB=blank();save();toast('已清空');render('hos')}};
}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function init(){css();nav();shell();bind();const h=location.hash.slice(1);show(document.getElementById(h)?h:(MODE==='lite'?'crm':'hos'));window.VCT50_HOSPITAL_OS={getData:()=>DB,save,show,mode:MODE};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
