/* VCT Clinical Intelligence 5.0-r08
 * Clinical workflow / emergency / trends / reassessment / fluid / medication safety /
 * next-best-test / differential / antimicrobial stewardship / pain / rounds / POMR /
 * imaging / specialty frameworks / dynamic red flags.
 * Safety: no fabricated doses; AI and decision support remain advisory and auditable.
 */
(function(){
'use strict';
const KEY='vct50_clinical_intelligence_v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date().toISOString();
const uid=p=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);
const el=id=>document.getElementById(id);
const patient=()=>window.VCT50_PATIENT_STATE?.getState?.()||window.vetPatientState5?.getState?.()||{};
const blank=()=>({version:1,updatedAt:now(),encounters:[],problems:[],observations:[],reassessments:[],fluids:[],medications:[],ddx:[],tests:[],antimicrobials:[],pain:[],rounds:[],pomr:[],imaging:[],specialty:[],timeline:[],audit:[]});
function load(){try{return Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{return blank();}}
let DB=load();
function save(){DB.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(DB));}
function audit(action,entity,id,meta={}){DB.audit.unshift({id:uid('aud'),at:now(),actor:'当前用户',action,entity,entityId:id,meta});DB.audit=DB.audit.slice(0,1000);save();}
function tl(type,text,meta={}){DB.timeline.unshift({id:uid('tl'),at:now(),type,text,meta});DB.timeline=DB.timeline.slice(0,2000);save();}
function val(id){return el(id)?.value?.trim()||''}
function num(id){const x=Number(el(id)?.value);return Number.isFinite(x)?x:null}
function card(title,body,cls=''){return `<div class="vct-ci-card ${cls}"><h3>${title}</h3>${body}</div>`}
function badge(s){return `<span class="vct-ci-badge">${esc(s)}</span>`}
function addStyles(){if(el('vctClinicalIntelligenceCss'))return;const s=document.createElement('style');s.id='vctClinicalIntelligenceCss';s.textContent=`
#vctClinicalIntelligence{margin-top:14px}.vct-ci-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.vct-ci-card{border:1px solid var(--line,#dbe5e2);border-radius:12px;background:#fff;padding:12px;margin:10px 0}.vct-ci-card h3{margin:0 0 8px}.vct-ci-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.vct-ci-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.vct-ci-form label{font-size:12px}.vct-ci-form input,.vct-ci-form select,.vct-ci-form textarea{width:100%;box-sizing:border-box}.vct-ci-form textarea{min-height:72px}.vct-ci-badge{display:inline-block;border-radius:999px;padding:3px 8px;background:#eef6f4;font-size:11px;margin:2px}.vct-ci-red{border-left:4px solid #dc2626;background:#fff5f5}.vct-ci-amber{border-left:4px solid #d97706;background:#fffaf0}.vct-ci-green{border-left:4px solid #16a34a;background:#f3fff5}.vct-ci-blue{border-left:4px solid #2563eb;background:#f4f8ff}.vct-ci-muted{color:#64748b}.vct-ci-table{width:100%;border-collapse:collapse;font-size:13px}.vct-ci-table th,.vct-ci-table td{padding:7px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}.vct-ci-score{font-size:28px;font-weight:700}.vct-ci-list{margin:6px 0 0 18px}.vct-ci-timeline{max-height:300px;overflow:auto}.vct-ci-tl{padding:7px;border-bottom:1px solid #e5e7eb}.vct-ci-chip{display:inline-block;padding:4px 7px;margin:2px;border:1px solid #dbe5e2;border-radius:8px;font-size:11px}.vct-ci-status{font-weight:600}@media(max-width:900px){.vct-ci-grid,.vct-ci-form{grid-template-columns:1fr}}` ;document.head.appendChild(s)}
function shell(){if(el('vctClinicalIntelligence'))return;const wrap=document.createElement('section');wrap.id='vctClinicalIntelligence';wrap.className='view';wrap.innerHTML=`<div class="card">
<h2>🧠 Clinical Intelligence OS · 5.0-r08</h2><p class="muted">以单一 Patient State / Encounter 为中心：Emergency → Problem List → Tests → Assessment → Treatment → Monitoring → Reassessment → Discharge / Follow-up。所有建议为临床辅助，不自动下医嘱。</p>
<div class="vct-ci-toolbar"><button class="primary" id="ciNewEncounter">新建当前就诊</button><button id="ciSyncPatient">同步当前 Patient State</button><button id="ciExport">导出临床智能数据</button><button id="ciReset">清空临床智能数据</button></div>
<div id="ciOverview"></div>
<div class="vct-ci-grid">
 <div class="vct-ci-card"><b>Emergency Cockpit 2.0</b><p>ABCDE + 动态红旗 + 优先级排序。</p><button id="ciGoEmergency">进入</button></div>
 <div class="vct-ci-card"><b>Clinical Workflow</b><p>统一病例状态、问题、检查、治疗和复评。</p><button id="ciGoWorkflow">进入</button></div>
 <div class="vct-ci-card"><b>Trend Engine</b><p>生命体征、实验室、体重、I&O纵向趋势。</p><button id="ciGoTrend">进入</button></div>
</div></div>
<div class="card" id="ciEmergency"><h2>🚨 Emergency Cockpit 2.0</h2><div id="ciRedFlags"></div><div class="vct-ci-form"><label>A · Airway<input id="ciA" placeholder="气道是否通畅/异常"></label><label>B · Breathing<input id="ciB" placeholder="RR/effort/SpO₂/肺音"></label><label>C · Circulation<input id="ciC" placeholder="HR/BP/CRT/脉搏/灌注"></label><label>D · Disability<input id="ciD" placeholder="意识/神经/癫痫"></label><label>E · Exposure<input id="ciE" placeholder="体温/创伤/全身暴露"></label><label>立即问题<textarea id="ciImmediate"></textarea></label><label>当前体重 kg<input id="ciEW" type="number" step=".01"></label><label>尿量/灌注备注<textarea id="ciEUOP"></textarea></label></div><div class="vct-ci-toolbar"><button class="primary" id="ciAssessEmergency">运行急诊评估</button><button id="ciSaveEmergency">保存急诊快照</button></div><div id="ciEmergencyOut"></div></div>
<div class="card" id="ciWorkflow"><h2>🔄 Patient-centered Clinical Workflow</h2><div id="ciPatientSummary"></div><div class="vct-ci-form"><label>Encounter ID<input id="ciEncounterId"></label><label>就诊阶段<select id="ciStage"><option>分诊</option><option>初始评估</option><option>检查</option><option>治疗</option><option>监测</option><option>再评估</option><option>出院</option><option>复诊</option></select></label><label>主诉<textarea id="ciChief"></textarea></label><label>Problem List<textarea id="ciProblems" placeholder="问题1；问题2"></textarea></label><label>已知事实 Known Facts<textarea id="ciFacts"></textarea></label><label>临床推断 Clinical Inference<textarea id="ciInference"></textarea></label><label>鉴别 Differential<textarea id="ciDifferential"></textarea></label><label>建议 Recommendation<textarea id="ciRecommendation"></textarea></label><label>医生确认 Doctor Confirmed<textarea id="ciConfirmed"></textarea></label><label>已执行 Executed<textarea id="ciExecuted"></textarea></label></div><div class="vct-ci-toolbar"><button class="primary" id="ciSaveWorkflow">保存 Encounter</button><button id="ciPushProblem">写入 Problem List</button></div><div id="ciWorkflowOut"></div></div>
<div class="card" id="ciTrend"><h2>📈 Trend Engine</h2><div class="vct-ci-form"><label>指标<input id="ciTName" placeholder="CRE / K / Lactate / T / HR / RR / BW"></label><label>数值<input id="ciTValue" type="number" step=".01"></label><label>单位<input id="ciTUnit"></label><label>时间<input id="ciTTime" type="datetime-local"></label></div><button class="primary" id="ciAddTrend">记录指标</button><div id="ciTrendOut"></div></div>
<div class="card" id="ciReassess"><h2>🔁 Reassessment Engine</h2><div class="vct-ci-form"><label>干预/治疗<textarea id="ciRIntervention"></textarea></label><label>复评时间（min）<input id="ciRMinutes" type="number"></label><label>复评指标<textarea id="ciRTargets" placeholder="HR、BP、CRT、SpO₂、疼痛、乳酸、UOP等"></textarea></label><label>复评结果<textarea id="ciRResult"></textarea></label><label>反应<select id="ciRResponse"><option>未复评</option><option>改善</option><option>部分改善</option><option>无改善</option><option>恶化</option></select></label><label>下一步<textarea id="ciRNext"></textarea></label></div><button class="primary" id="ciSaveReassess">保存复评</button><div id="ciReassessOut"></div></div>
<div class="card"><h2>💧 Fluid as Drug 2.0</h2><div class="vct-ci-form"><label>体重 kg<input id="ciFW" type="number" step=".01"></label><label>IV 输入 mL<input id="ciFIV" type="number" step=".1"></label><label>PO/EN 输入 mL<input id="ciFPO" type="number" step=".1"></label><label>药物/其他输入 mL<input id="ciFOther" type="number" step=".1"></label><label>尿液输出 mL<input id="ciFUOP" type="number" step=".1"></label><label>呕吐/引流/其他输出 mL<input id="ciFOut" type="number" step=".1"></label><label>小时数<input id="ciFH" type="number" value="24"></label><label>容量风险<select id="ciFVR"><option>未知</option><option>低</option><option>中</option><option>高</option></select></label><label>监测备注<textarea id="ciFNote"></textarea></label></div><button class="primary" id="ciCalcFluid">计算并记录</button><div id="ciFluidOut"></div></div>
<div class="card"><h2>💊 Medication Safety 2.0</h2><div class="vct-ci-form"><label>药物/制剂<input id="ciMDrug"></label><label>剂型/浓度<input id="ciMForm"></label><label>物种<input id="ciMSpecies" value="当前患者"></label><label>剂量来源<input id="ciMSource" placeholder="当前制剂标签 / guideline / 文献 / 待核验"></label><label>适应证<textarea id="ciMIndication"></textarea></label><label>禁忌/警示<textarea id="ciMContra"></textarea></label><label>肾/肝状态<textarea id="ciMOrgan"></textarea></label><label>联合用药<textarea id="ciMConcomitant"></textarea></label><label>Evidence Tier<select id="ciMTier"><option>A</option><option>B</option><option>C</option><option>D</option></select></label></div><button class="primary" id="ciCheckMed">运行处方安全闸门</button><div id="ciMedOut"></div></div>
<div class="card"><h2>🔬 Next Best Test</h2><div class="vct-ci-form"><label>当前问题<textarea id="ciNProblem"></textarea></label><label>已有检查<textarea id="ciNExisting"></textarea></label><label>关键未确定问题<textarea id="ciNUncertainty"></textarea></label><label>候选检查<textarea id="ciNTests" placeholder="每行一项"></textarea></label></div><button class="primary" id="ciRankTests">排序下一最佳检查</button><div id="ciTestOut"></div></div>
<div class="card"><h2>🧩 Differential Engine 2.0</h2><div class="vct-ci-form"><label>综合征/主问题<input id="ciDSyndrome" placeholder="如 黄疸、呼吸困难、呕吐"></label><label>物种<select id="ciDSpecies"><option>猫</option><option>犬</option><option>其他</option></select></label><label>支持证据<textarea id="ciDSupport"></textarea></label><label>反对证据<textarea id="ciDAgainst"></textarea></label><label>缺失证据<textarea id="ciDMissing"></textarea></label><label>候选鉴别<textarea id="ciDDxList" placeholder="每行一个"></textarea></label></div><button class="primary" id="ciRankDdx">生成鉴别排序</button><div id="ciDdxOut"></div></div>
<div class="card"><h2>🦠 Antimicrobial Stewardship 2.0</h2><div class="vct-ci-form"><label>感染指征/感染源<textarea id="ciAIndication"></textarea></label><label>经验性还是靶向<select id="ciAEmp"><option>经验性</option><option>靶向</option></select></label><label>培养/药敏状态<select id="ciACulture"><option>未采样</option><option>已采样待结果</option><option>结果已回</option><option>阴性/未支持</option></select></label><label>开始日期<input id="ciAStart" type="date"></label><label>计划再评估日期<input id="ciAReview" type="date"></label><label>计划停止日期<input id="ciAStop" type="date"></label><label>拟用抗菌药<textarea id="ciADrug"></textarea></label><label>降阶/停药条件<textarea id="ciADeescalate"></textarea></label></div><button class="primary" id="ciSaveAbx">保存抗菌药管理记录</button><div id="ciAbxOut"></div></div>
<div class="card"><h2>🩹 Pain 2.0</h2><div class="vct-ci-form"><label>物种<input id="ciPSpecies"></label><label>量表<input id="ciPScale" placeholder="如已验证的犬/猫疼痛量表"></label><label>基线评分<input id="ciPBase" type="number" step=".1"></label><label>干预<textarea id="ciPIntervention"></textarea></label><label>复评评分<input id="ciPRe" type="number" step=".1"></label><label>功能/行为变化<textarea id="ciPFunction"></textarea></label></div><button class="primary" id="ciSavePain">保存疼痛复评</button><div id="ciPainOut"></div></div>
<div class="card"><h2>🏥 Daily Rounds</h2><div class="vct-ci-form"><label>夜间事件<textarea id="ciROvernight"></textarea></label><label>生命体征<textarea id="ciRVitals"></textarea></label><label>实验室趋势<textarea id="ciRLabs"></textarea></label><label>营养<textarea id="ciRNutrition"></textarea></label><label>Fluid/I&O<textarea id="ciRFluid"></textarea></label><label>Problems<textarea id="ciRProblems"></textarea></label><label>Assessment<textarea id="ciRAssessment"></textarea></label><label>Plan<textarea id="ciRPlan"></textarea></label></div><button class="primary" id="ciSaveRounds">保存每日查房</button><div id="ciRoundsOut"></div></div>
<div class="card"><h2>📝 POMR 2.0</h2><div class="vct-ci-form"><label>Problem #<input id="ciPomrNo" placeholder="1"></label><label>Problem 名称<input id="ciPomrName"></label><label>S · Subjective<textarea id="ciPomrS"></textarea></label><label>O · Objective<textarea id="ciPomrO"></textarea></label><label>A · Assessment<textarea id="ciPomrA"></textarea></label><label>P · Plan<textarea id="ciPomrP"></textarea></label></div><button class="primary" id="ciSavePomr">保存 Problem-oriented 记录</button><div id="ciPomrOut"></div></div>
<div class="card"><h2>🩻 Imaging Workstation 基础框架</h2><div class="vct-ci-form"><label>Modalality<select id="ciIMod"><option>X-ray</option><option>Ultrasound</option><option>CT</option><option>MRI</option><option>Endoscopy</option></select></label><label>Region<input id="ciIRegion"></label><label>Findings<textarea id="ciIFindings"></textarea></label><label>Key negatives<textarea id="ciINeg"></textarea></label><label>Impression<textarea id="ciIImpression"></textarea></label><label>Differentials<textarea id="ciIDdx"></textarea></label><label>Recommendation<textarea id="ciIRec"></textarea></label></div><button class="primary" id="ciSaveImaging">保存影像结构化报告</button><div id="ciImagingOut"></div></div>
<div class="card"><h2>🧬 Specialty Frameworks</h2><div class="vct-ci-toolbar"><select id="ciSpecialty"><option>Emergency / Critical Care</option><option>Internal Medicine</option><option>Cardiology</option><option>Nephrology</option><option>Gastroenterology</option><option>Neurology</option><option>Oncology</option><option>Dermatology</option><option>Endocrinology</option><option>Infectious Disease</option><option>Ophthalmology</option><option>Reproduction</option><option>Dentistry</option><option>Exotic Companion Animal</option></select><button class="primary" id="ciSpecialtyBuild">生成专科工作表</button></div><div id="ciSpecialtyOut"></div></div>
<div class="card"><h2>🧾 Clinical Timeline / Audit</h2><div id="ciTimeline"></div></div>
</div>`;document.body.appendChild(wrap)}
function patientSummary(){const p=patient();el('ciPatientSummary').innerHTML=card('当前 Patient State',`<div class="vct-ci-grid"><div>Patient ID<br><b>${esc(p.patientId||'未设置')}</b></div><div>患者<br><b>${esc(p.petName||'未命名')}</b> · ${esc(p.species||'')}</div><div>体重<br><b>${esc(p.weight||'')}</b> kg</div><div>主诉<br>${esc(p.chief||'')}</div><div>诊断<br>${esc(p.diagnosis||'')}</div><div>当前用药<br>${esc(p.currentMeds||'')}</div></div>`,'vct-ci-blue')}
function overview(){const p=patient();const reds=dynamicRedFlags(p);el('ciOverview').innerHTML=`<div class="vct-ci-grid"><div class="vct-ci-card"><span>当前患者</span><div class="vct-ci-score">${esc(p.petName||'—')}</div>${badge(p.species||'未知物种')}</div><div class="vct-ci-card"><span>临床记录</span><div class="vct-ci-score">${DB.encounters.length}</div><span class="vct-ci-muted">encounters</span></div><div class="vct-ci-card"><span>动态红旗</span><div class="vct-ci-score">${reds.length}</div><span class="vct-ci-muted">需复核</span></div></div>`}
function dynamicRedFlags(p){const r=[];const w=Number(p.weight);const k=Number(p.potassium);const cre=Number(p.creatinine);const glu=Number(p.glucose);if(Number.isFinite(k)&&k>=6.0)r.push({level:'P0',text:'Hyperkalemia 高钾血症：需要结合ECG、尿量和临床状态立即复核。'});if(Number.isFinite(glu)&&glu<3.0)r.push({level:'P0',text:'Hypoglycemia 低血糖：立即确认测量、临床症状和纠正需求。'});if(Number.isFinite(cre)&&cre>=300)r.push({level:'P1',text:'明显氮质血症/肾功能异常：结合趋势、尿量、容量状态和实验室参考区间复核。'});if(!Number.isFinite(w)||w<=0)r.push({level:'P1',text:'缺少当前体重：药物/液体相关计算无法安全进行。'});if(!p.species)r.push({level:'P1',text:'缺少物种：物种特异量表、药物和参考区间无法可靠匹配。'});return r}
function renderRedFlags(){const r=dynamicRedFlags(patient());el('ciRedFlags').innerHTML=r.length?r.map(x=>`<div class="vct-ci-card ${x.level==='P0'?'vct-ci-red':'vct-ci-amber'}"><b>${x.level}</b> · ${esc(x.text)}</div>`).join(''):`<div class="vct-ci-card vct-ci-green">当前 Patient State 未触发本引擎内的结构化红旗；这不等于排除急症。</div>`}
function emergency(){const vals=['ciA','ciB','ciC','ciD','ciE'].map(id=>val(id));const immediate=val('ciImmediate');const out=[];vals.forEach((x,i)=>{if(!x)out.push(`${['A','B','C','D','E'][i]} 未完成评估`)});if(immediate)out.push(`立即问题：${immediate}`);const p=patient();const r=dynamicRedFlags(p);el('ciEmergencyOut').innerHTML=`<div class="vct-ci-card ${r.some(x=>x.level==='P0')?'vct-ci-red':'vct-ci-blue'}"><b>急诊状态</b><ul class="vct-ci-list">${out.length?out.map(esc).map(x=>`<li>${x}</li>`).join(''):'ABCDE均已填写，请结合原始数据复核。'}</ul><p>顺序：Airway → Breathing → Circulation → Disability → Exposure；支持治疗与病因诊断并行。</p></div>`}
function saveEmergency(){const id=uid('enc');const e={id,patientId:patient().patientId||'',createdAt:now(),type:'Emergency',abc:{A:val('ciA'),B:val('ciB'),C:val('ciC'),D:val('ciD'),E:val('ciE')},immediate:val('ciImmediate'),weight:num('ciEW'),uop:val('ciEUOP'),redFlags:dynamicRedFlags(patient())};DB.encounters.unshift(e);audit('create','emergency',id);tl('Emergency',`急诊快照：${patient().petName||'当前患者'}`,{id});el('ciEmergencyOut').innerHTML+='<div class="vct-ci-card vct-ci-green">急诊快照已保存并进入 Timeline。</div>';overview();timeline()}
function saveWorkflow(){const id=val('ciEncounterId')||uid('enc');const e={id,patientId:patient().patientId||'',createdAt:now(),stage:val('ciStage'),chief:val('ciChief'),problems:val('ciProblems'),facts:val('ciFacts'),inference:val('ciInference'),differential:val('ciDifferential'),recommendation:val('ciRecommendation'),confirmed:val('ciConfirmed'),executed:val('ciExecuted')};DB.encounters.unshift(e);audit('upsert','encounter',id,{stage:e.stage});tl('Workflow',`${e.stage} · ${patient().petName||'当前患者'}`,{encounterId:id});el('ciWorkflowOut').innerHTML='<div class="vct-ci-card vct-ci-green">Encounter 已保存。建议继续记录检查结果、治疗、监测与再评估。</div>';overview();timeline()}
function pushProblem(){const p=val('ciProblems');if(!p)return;const arr=p.split(/[；;\n]+/).map(x=>x.trim()).filter(Boolean);arr.forEach(name=>{const id=uid('prob');DB.problems.unshift({id,name,status:'active',patientId:patient().patientId||'',createdAt:now(),source:'Clinical Intelligence'});audit('create','problem',id,{name});tl('Problem',`新增问题：${name}`)});el('ciWorkflowOut').innerHTML='<div class="vct-ci-card vct-ci-blue">Problem List 已更新。</div>';timeline()}
function addTrend(){const name=val('ciTName'),v=num('ciTValue');if(!name||v===null)return;DB.observations.unshift({id:uid('obs'),patientId:patient().patientId||'',name,value:v,unit:val('ciTUnit'),at:val('ciTTime')?new Date(val('ciTTime')).toISOString():now()});audit('create','observation',DB.observations[0].id,{name,value:v});renderTrend();tl('Trend',`${name} = ${v} ${val('ciTUnit')}`)}
function renderTrend(){const groups={};DB.observations.forEach(o=>{(groups[o.name]??=[]).push(o)});el('ciTrendOut').innerHTML=Object.entries(groups).map(([n,a])=>{a.sort((x,y)=>new Date(x.at)-new Date(y.at));const last=a[a.length-1],prev=a[a.length-2];const delta=prev?last.value-prev.value:null;const dir=delta===null?'—':delta>0?'↑':delta<0?'↓':'→';return `<div class="vct-ci-card"><b>${esc(n)}</b> ${badge(last.unit||'')} <span class="vct-ci-status">${last.value} ${dir}</span><div class="vct-ci-muted">${a.slice(-8).map(x=>`${new Date(x.at).toLocaleString()} · ${x.value} ${esc(x.unit||'')}`).join('<br>')}</div></div>`}).join('')||'<span class="vct-ci-muted">暂无趋势数据。</span>'}
function saveReassess(){const x={id:uid('re'),patientId:patient().patientId||'',at:now(),intervention:val('ciRIntervention'),minutes:num('ciRMinutes'),targets:val('ciRTargets'),result:val('ciRResult'),response:val('ciRResponse'),next:val('ciRNext')};DB.reassessments.unshift(x);audit('create','reassessment',x.id,{response:x.response});tl('Reassessment',`${x.response}：${x.intervention}`);el('ciReassessOut').innerHTML=`<div class="vct-ci-card ${x.response==='恶化'?'vct-ci-red':x.response==='无改善'?'vct-ci-amber':'vct-ci-green'}"><b>复评：${esc(x.response)}</b><p>${esc(x.result)}</p><p>下一步：${esc(x.next)}</p></div>`;timeline()}
function calcFluid(){const w=num('ciFW'),iv=num('ciFIV')||0,po=num('ciFPO')||0,other=num('ciFOther')||0,u=num('ciFUOP')||0,out=num('ciFOut')||0,h=num('ciFH')||24;if(!w||w<=0){el('ciFluidOut').innerHTML='<div class="vct-ci-red">缺少有效体重。</div>';return}const input=iv+po+other,totalOut=u+out,balance=input-totalOut;const x={id:uid('fl'),patientId:patient().patientId||'',at:now(),weight:w,input:{iv,po,other,total:input},output:{uop:u,other:out,total:totalOut},balance,mlkgday:balance/w*(24/h),risk:val('ciFVR'),note:val('ciFNote')};DB.fluids.unshift(x);audit('create','fluid',x.id,{balance});tl('Fluid',`I&O balance ${balance.toFixed(1)} mL`,{risk:x.risk});const risk=x.risk==='高'?'vct-ci-red':balance>0&&x.risk!=='低'?'vct-ci-amber':'vct-ci-blue';el('ciFluidOut').innerHTML=`<div class="vct-ci-card ${risk}"><b>Fluid Balance</b><div class="vct-ci-score">${balance.toFixed(1)} mL</div><div>输入 ${input.toFixed(1)} mL · 输出 ${totalOut.toFixed(1)} mL · ${h} h</div><div>按当前体重/时长折算：${x.mlkgday.toFixed(2)} mL/kg/日（仅数学结果，不代表治疗目标）</div><p>容量风险：${esc(x.risk)}。需结合体重趋势、肺部状态、血压、灌注、UOP及基础心肾疾病判断。</p></div>`}
function medSafety(){const drug=val('ciMDrug');if(!drug){el('ciMedOut').innerHTML='<div class="vct-ci-red">请输入药物。</div>';return}const warnings=[];if(!val('ciMSource')||val('ciMSource').includes('待核验'))warnings.push('剂量/制剂来源未完成核验。');if(!val('ciMIndication'))warnings.push('适应证未明确。');if(!val('ciMContra'))warnings.push('禁忌/警示未记录。');if(!val('ciMOrgan'))warnings.push('肝肾状态未记录。');if(!val('ciMConcomitant'))warnings.push('联合用药未记录，无法完成相互作用审查。');const x={id:uid('med'),patientId:patient().patientId||'',at:now(),drug,form:val('ciMForm'),species:val('ciMSpecies'),source:val('ciMSource'),indication:val('ciMIndication'),contra:val('ciMContra'),organ:val('ciMOrgan'),concomitant:val('ciMConcomitant'),tier:val('ciMTier'),warnings};DB.medications.unshift(x);audit('safety_gate','medication',x.id,{warnings:warnings.length,tier:x.tier});tl('Medication Safety',`${drug} · ${warnings.length?'待核验':'基础字段完整'}`);el('ciMedOut').innerHTML=`<div class="vct-ci-card ${warnings.length?'vct-ci-amber':'vct-ci-green'}"><b>${esc(drug)} · Safety Gate</b>${warnings.length?`<ul class="vct-ci-list">${warnings.map(esc).map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p>基础安全字段已填写；仍需核对当前制剂标签、指南和患者实时状态。</p>'}<p>Evidence Tier：${esc(x.tier)}</p><b>禁止自动行为：</b>不自动下处方、不自动执行给药。</div>`}
function rankTests(){const list=val('ciNTests').split(/\n|；|;/).map(x=>x.trim()).filter(Boolean);const uncertainty=val('ciNUncertainty');const scored=list.map((t,i)=>({t,score:Math.max(0,100-i*8)+(uncertainty?20:0),reason:uncertainty?`直接针对当前关键不确定性：${uncertainty}`:'请由医生评估其对当前诊断概率和紧急处理的影响'})).sort((a,b)=>b.score-a.score);el('ciTestOut').innerHTML=scored.map((x,i)=>`<div class="vct-ci-card ${i===0?'vct-ci-blue':''}"><b>${i+1}. ${esc(x.t)}</b> ${badge('候选') }<p>${esc(x.reason)}</p><small>排序分为启发式，不是验证过的概率模型。</small></div>`).join('')||'<div class="vct-ci-muted">请输入候选检查。</div>';const x={id:uid('test'),at:now(),patientId:patient().patientId||'',problem:val('ciNProblem'),existing:val('ciNExisting'),uncertainty,ranking:scored};DB.tests.unshift(x);audit('rank','next-best-test',x.id);tl('Next Best Test',`生成${scored.length}项候选检查`)}
function rankDdx(){const list=val('ciDDxList').split(/\n|；|;/).map(x=>x.trim()).filter(Boolean);const support=val('ciDSupport'),against=val('ciDAgainst'),missing=val('ciDMissing');const scored=list.map((d,i)=>({d,rank:i+1,support,against,missing}));el('ciDdxOut').innerHTML=scored.map((x,i)=>`<div class="vct-ci-card ${i===0?'vct-ci-blue':''}"><b>${i+1}. ${esc(x.d)}</b><div><span class="vct-ci-chip">支持证据：${esc(support||'待补')}</span><span class="vct-ci-chip">反对证据：${esc(against||'待补')}</span><span class="vct-ci-chip">缺失证据：${esc(missing||'待补')}</span></div></div>`).join('')||'<div class="vct-ci-muted">请输入候选鉴别。</div>';const x={id:uid('ddx'),at:now(),patientId:patient().patientId||'',syndrome:val('ciDSyndrome'),species:val('ciDSpecies'),support,against,missing,ranking:scored};DB.ddx.unshift(x);audit('rank','differential',x.id);tl('Differential',`生成${scored.length}项鉴别排序`)}
function saveAbx(){const x={id:uid('abx'),at:now(),patientId:patient().patientId||'',indication:val('ciAIndication'),strategy:val('ciAEmp'),culture:val('ciACulture'),start:val('ciAStart'),review:val('ciAReview'),stop:val('ciAStop'),drug:val('ciADrug'),deescalate:val('ciADeescalate')};DB.antimicrobials.unshift(x);audit('create','antimicrobial',x.id);tl('Antimicrobial',`${x.strategy} · review ${x.review||'未设'}`);const warn=x.culture==='未采样'?'若临床允许，需考虑在抗菌药前采集合适培养/药敏样本。':'按结果进行继续、降阶、停药或调整的再评估。';el('ciAbxOut').innerHTML=`<div class="vct-ci-card vct-ci-amber"><b>Antimicrobial Timeout</b><p>${esc(warn)}</p><p>再评估：${esc(x.review||'未设置')} · 计划停止：${esc(x.stop||'未设置')}</p></div>`}
function savePain(){const b=num('ciPBase'),r=num('ciPRe');const delta=b!==null&&r!==null?r-b:null;const x={id:uid('pain'),at:now(),patientId:patient().patientId||'',species:val('ciPSpecies')||patient().species,scale:val('ciPScale'),baseline:b,intervention:val('ciPIntervention'),reassessment:r,function:val('ciPFunction'),delta};DB.pain.unshift(x);audit('create','pain',x.id,{delta});tl('Pain',`疼痛复评 ${r??'未评分'}`);el('ciPainOut').innerHTML=`<div class="vct-ci-card ${delta===null?'vct-ci-blue':delta<0?'vct-ci-green':delta>0?'vct-ci-red':'vct-ci-amber'}"><b>疼痛趋势</b><div>${b??'—'} → ${r??'—'} ${delta===null?'':'（变化 '+delta.toFixed(1)+'）'}</div><p>使用物种适用且经过验证的疼痛量表；分数变化需结合功能和行为表现。</p></div>`}
function saveRounds(){const x={id:uid('round'),at:now(),patientId:patient().patientId||'',overnight:val('ciROvernight'),vitals:val('ciRVitals'),labs:val('ciRLabs'),nutrition:val('ciRNutrition'),fluid:val('ciRFluid'),problems:val('ciRProblems'),assessment:val('ciRAssessment'),plan:val('ciRPlan')};DB.rounds.unshift(x);audit('create','round',x.id);tl('Rounds',`每日查房：${patient().petName||'当前患者'}`);el('ciRoundsOut').innerHTML='<div class="vct-ci-card vct-ci-green">Daily Rounds 已保存。</div>'}
function savePomr(){const x={id:uid('pomr'),at:now(),patientId:patient().patientId||'',number:val('ciPomrNo'),problem:val('ciPomrName'),S:val('ciPomrS'),O:val('ciPomrO'),A:val('ciPomrA'),P:val('ciPomrP')};DB.pomr.unshift(x);audit('create','pomr',x.id);tl('POMR',`Problem ${x.number}: ${x.problem}`);el('ciPomrOut').innerHTML='<div class="vct-ci-card vct-ci-green">POMR 已保存。</div>'}
function saveImaging(){const x={id:uid('img'),at:now(),patientId:patient().patientId||'',modality:val('ciIMod'),region:val('ciIRegion'),findings:val('ciIFindings'),negatives:val('ciINeg'),impression:val('ciIImpression'),ddx:val('ciIDdx'),recommendation:val('ciIRec')};DB.imaging.unshift(x);audit('create','imaging',x.id);tl('Imaging',`${x.modality} · ${x.region}`);el('ciImagingOut').innerHTML='<div class="vct-ci-card vct-ci-green">结构化影像报告已保存。AI影像意见必须与原始影像及兽医复核结合。</div>'}
const specialtyMap={
'Emergency / Critical Care':['ABCDE','Shock/perfusion','Respiratory distress','Pain','Fluid balance','Reassessment'],
'Internal Medicine':['Problem List','Minimum database','Syndrome localization','Trend','Reassessment'],
'Cardiology':['Perfusion','Respiratory status','ECG','Blood pressure','Echo findings','Volume status'],
'Nephrology':['UOP','Creatinine trend','Electrolytes','Urinalysis','Blood pressure','Fluid balance'],
'Gastroenterology':['Vomiting/diarrhea','Nutrition','Pain','Pancreatic/hepatobiliary','Imaging','Reassessment'],
'Neurology':['Mentation','Localization','Seizure burden','Pain','Blood glucose/electrolytes','Imaging'],
'Oncology':['Tumor burden','Staging','Pain','Nutrition','Treatment toxicity','Quality of life'],
'Dermatology':['Primary lesions','Distribution','Cytology','Parasite/fungal testing','Diet/therapy trial','Response'],
'Endocrinology':['Glucose','Electrolytes','Hormonal testing','Urine output','Blood pressure','Trend'],
'Infectious Disease':['Exposure','Isolation','Sampling','PCR/culture','Antimicrobial stewardship','Public/household risk'],
'Ophthalmology':['Vision','Pain','Cornea','IOP','Fundus','Urgency'],
'Reproduction':['Cycle/status','Pregnancy','Ultrasound','CBC/chemistry','Infection','Surgical planning'],
'Dentistry':['Oral pain','Periodontal findings','Dental chart','Imaging','Anesthesia risk','Post-op plan'],
'Exotic Companion Animal':['Species-specific anatomy','Husbandry','Nutrition','Pain','Temperature/environment','Species-specific references']};
function buildSpecialty(){const s=val('ciSpecialty'),items=specialtyMap[s]||[];el('ciSpecialtyOut').innerHTML=card(s,`<div class="vct-ci-grid">${items.map(x=>`<div class="vct-ci-card"><b>${esc(x)}</b><textarea placeholder="记录${esc(x)}"></textarea></div>`).join('')}</div><div class="vct-ci-muted">这是结构化专科工作表框架，不替代专科指南或物种特异资料。</div>`,'vct-ci-blue');DB.specialty.unshift({id:uid('sp'),at:now(),patientId:patient().patientId||'',specialty:s,items});audit('create','specialty',DB.specialty[0].id);tl('Specialty',`打开专科工作表：${s}`)}
function timeline(){el('ciTimeline').innerHTML=DB.timeline.slice(0,80).map(x=>`<div class="vct-ci-tl"><b>${esc(x.type)}</b> · ${new Date(x.at).toLocaleString()}<br>${esc(x.text)}</div>`).join('')||'<span class="vct-ci-muted">暂无临床智能事件。</span>'}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:'5.0-r08',exportedAt:now(),patient:patient(),data:DB},null,2)],{type:'application/json'}));a.download='vct50-clinical-intelligence-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function sync(){const p=patient();['ciEW','ciFW'].forEach(id=>{if(el(id)&&p.weight)el(id).value=p.weight});['ciPSpecies','ciMSpecies'].forEach(id=>{if(el(id)&&p.species)el(id).value=p.species});el('ciEncounterId').value=p.patientId?`enc-${p.patientId}`:'';el('ciChief').value=p.chief||'';patientSummary();overview();renderRedFlags()}
function bind(){el('ciNewEncounter').onclick=()=>{sync();el('ciStage').value='初始评估';el('ciWorkflow').scrollIntoView({behavior:'smooth'});};el('ciSyncPatient').onclick=sync;el('ciExport').onclick=exportData;el('ciReset').onclick=()=>{if(confirm('确认清空 Clinical Intelligence 本机数据？')){DB=blank();save();overview();timeline();alert('已清空。')}};el('ciGoEmergency').onclick=()=>el('ciEmergency').scrollIntoView({behavior:'smooth'});el('ciGoWorkflow').onclick=()=>el('ciWorkflow').scrollIntoView({behavior:'smooth'});el('ciGoTrend').onclick=()=>el('ciTrend').scrollIntoView({behavior:'smooth'});el('ciAssessEmergency').onclick=emergency;el('ciSaveEmergency').onclick=saveEmergency;el('ciSaveWorkflow').onclick=saveWorkflow;el('ciPushProblem').onclick=pushProblem;el('ciAddTrend').onclick=addTrend;el('ciSaveReassess').onclick=saveReassess;el('ciCalcFluid').onclick=calcFluid;el('ciCheckMed').onclick=medSafety;el('ciRankTests').onclick=rankTests;el('ciRankDdx').onclick=rankDdx;el('ciSaveAbx').onclick=saveAbx;el('ciSavePain').onclick=savePain;el('ciSaveRounds').onclick=saveRounds;el('ciSavePomr').onclick=savePomr;el('ciSaveImaging').onclick=saveImaging;el('ciSpecialtyBuild').onclick=buildSpecialty;window.addEventListener('vct50:patient-change',sync)}
function init(){addStyles();shell();bind();sync();renderTrend();timeline();window.VCT50_CLINICAL_INTELLIGENCE={getData:()=>DB,refresh:sync,dynamicRedFlags};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
