import fs from 'node:fs';
import assert from 'node:assert/strict';
const js=fs.readFileSync('clinical_os_complete_5.0.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
assert.match(js,/clinical_os_complete/);
assert.match(js,/Dynamic Lab Trend/);
assert.match(js,/SOAP \/ POMR/);
assert.match(js,/Treatment Goals/);
assert.match(js,/Inpatient Task Board/);
assert.match(js,/Medication Safety Engine/);
assert.match(js,/Fluid as Drug/);
assert.match(js,/Pain Workbench/);
assert.match(js,/Evidence Library/);
assert.match(js,/AI Candidate/);
assert.match(js,/VHS/);
assert.match(js,/IRIS/);
assert.match(js,/ACVIM/);
assert.match(js,/MGCS/);
assert.match(js,/Triadan/);
assert.match(js,/TPA\/TPLO\/TTA/);
assert.match(js,/Exotics/);
assert.match(html,/clinical_os_complete_5\.0\.js/);
assert.match(sw,/clinical_os_complete_5\.0\.js/);
assert.match(sw,/final-complete/);
const drugs=JSON.parse(fs.readFileSync('data/drugs.json','utf8'));
const leaves=JSON.parse(fs.readFileSync('data/drug_leaflets_5.0.json','utf8'));
function countLeaves(x){if(!x||typeof x!=='object')return 0;if(Array.isArray(x))return x.reduce((n,v)=>n+countLeaves(v),0);if(x.generic_name_zh||x.id)return 1;return Object.values(x).reduce((n,v)=>n+countLeaves(v),0)}
assert.equal(countLeaves(drugs),427);
assert.equal(countLeaves(leaves),427);
console.log('clinical OS complete regression: OK');
